### ISSUE TITLE
Current issues with Legacy Mac Guide

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#102]
At the moment, we're currently preparing a [new guide for legacy Macs to run newer OSes](https://dortania.github.io/OpenCore-For-Legacy-Macs/), however there's some implantation details that need to be resolved first:

* [ ] USB Issues
  * [ ] Documenting broken IOHIDFamily in recovery
  * [ ] Documenting USB renames and map injection
  * [ ] USB Video injection
* [ ] Audio issues
  * [ ] Analog audio
  * [ ] Digital audio
* [ ] GPU Acceleration issues(Big Sur)
  * [ ] Framebuffer Injection
  * [ ] Proper hardware acceleration
* [ ] Airdrop issues
  * [ ] Newer SMBIOS with older hardware fail to show Airdrop in menu
    * This is due to macOS assuming 2012+ SMBIOS support Airdrop 2.0
* [ ]  Networking issues
  * [ ] [BCM4321 and 4328 injection](https://github.com/khronokernel/IO80211-Patches)
    * Fails to inject
  * [ ] [BCM4331 injection](https://github.com/khronokernel/IO80211-Patches)
    * Fails to attach

For audio issues, we plan to add support for the CS4206 and RTL885 codecs to AppleALC however our MacBook7,1 model is having some issues with our current build.

### Ref:

BCM4331 issue:
```
[    1.375732]: AirPort_Brcm4360::init AirPortFamily_kexts-1437.3 "AirPortFamily_kexts-1437.3" Oct 12 2019 09:39:16
[    1.375770]: ARPT: 1.375769: AirPort_Brcm43XX:probe:, this[0x8dda05392385d865]  score[1400]
[    1.375824]: ARPT: 1.375823: AirPort_Brcm43XX::start: Failed PCIe configuration, this[0x8dda05392385d865] vendor[0x000014e4] device[0x000034ba], chip: vid[0x14e4] did[0x4331] bar0[0xc1900004]
```

**Comment by 1alessandro1** [comment]
I would add the fact that with the OpenCore-Post-Install guide isn't mentioned how to generate C&P States with 1st gen CPUs (unfortunately ssdtprgen only mentions sandy bridge and up). 
So maybe we could [@SergeySlice](https://github.com/SergeySlice) or clover developers more documentation on that feature and if there is a way to create custom tables from ACPI
