### ISSUE TITLE
ApECID different from 0 booting recovery

### ISSUE THREAD

**Issue by josemmc95** [dortania/bugtracker#103]
I don't know if it's a bug in your guide or a mistake I made.

I read that before setting ApECID, we needed to boot in recovery and run a command.

I did that and then changed the ApECID to a random number like you showed in the guide.

When setting the ApECID after running the command, macOS reboots to recovery.

I tried to run the command again to personalize the volume with the ApECID set but it says that can't personalize the volume.

Is there any way to fix this or I'm just doing something wrong?

I need to set ApECID to 0 to be able to boot, if different from 0, it reboots to recovery.

If the command must be run after setting ApECID, you should write a note in the guide, because I run it before setting the ApECID and now I can't boot with a different ApECID.

Thank you in advanced!

**Comment by khronokernel** [comment]
> can't personalize the volume.

Ensure you're connected to the internet when in recovery, as otherwise the personalization fails since it cannot verify your files with Apple's servers.

> If the command must be run after setting ApECID, you should write a note in the guide, because I run it before setting the ApECID and now I can't boot with a different ApECID.

Yeah the wording in the guide is a bit misleading, will update it. But to answer, yes, set the ApECID value *before* running the commands, as macOS has no Secure Enclave identifier to use for the personalization

**Comment by josemmc95** [comment]
> > can't personalize the volume.
> 
> Ensure you're connected to the internet when in recovery, as otherwise the personalization fails since it cannot verify your files with Apple's servers.
> 
> > If the command must be run after setting ApECID, you should write a note in the guide, because I run it before setting the ApECID and now I can't boot with a different ApECID.
> 
> Yeah the wording in the guide is a bit misleading, will update it. But to answer, yes, set the ApECID value _before_ running the commands, as macOS has no Secure Enclave identifier to use for the personalization

Perfect! Fixed it connecting to the internet!

Thanks!
