### ISSUE TITLE
Sometimes no touchpad driver with Filevault enabled

### ISSUE THREAD

**Issue by josemmc95** [dortania/bugtracker#104]
I realized that with Filevault enabled, sometimes the touchpad doesn't work.

It's a I2C Elan.

I first noticed yesterday when upgrading to the latest suplemental update.

Is it a known bug and is there a solution?

If I need to send logs, could you please tell me how to get them? I've never used the logs.

Thank you in advanced!

Edit: Touchpad not working on OpenCore external picker neither and when typing the password to decrypt ssd.

**Comment by khronokernel** [comment]
With regards to FileVault, they rely on firmware based support and not with kexts. So if your OEM didn't write any I2C drivers for UEFI(or incorrectly most of the time), there won't be any drivers for FileVault to use. 

And regards to the I2C device not working in macOS, that will need to be directed towards the correct author. ie. [VoodooI2C](https://github.com/VoodooI2C/VoodooI2C), their README has some info on generating logs.

Hope that can clear things up
