### ISSUE TITLE
Kernel Panic on first reboot installing Big Sur

### ISSUE THREAD

**Issue by josemmc95** [dortania/bugtracker#105]
I'm having this kernel panic when trying to update to Big Sur. It occurs the first time the installer reboots you to the macOS Installer volume. It also occurs when trying to boot "Install macOS Big Sur" from an USB.

I'm using OC 0.6.3 with all kexts updated.

I also tried adding CtlnaAHCIPort.kext with MinKernel 20.0.0 but it doesn't help.

![99073607-845e9a00-25b6-11eb-8f15-fc789ee6ad7c](https://user-images.githubusercontent.com/62221854/99085437-77e33d00-25c8-11eb-9bb4-f0767a41b468.jpg)

[EFI.zip](https://github.com/dortania/bugtracker/files/5537497/EFI.zip)
[opencore-2020-11-13-135440.txt](https://github.com/dortania/bugtracker/files/5537499/opencore-2020-11-13-135440.txt)

**Comment by khronokernel** [comment]
You’re injecting 2 copies of VoodooInput, 1 from VoodooPS2 and one from VoodooI2C. Disable one of them in your config.plist

**Comment by josemmc95** [comment]
> You’re injecting 3 copies of VoodooInput, 1 from VoodooPS2, 1 from VoodooI2C, and 1 standalone. Disable two of them in your config.plist

I don't know why I had the standalone VoodooInput in the folder... I deleted it and disabled the one from PS2Controller and it worked.

Thank you a lot! ☺️
