### ISSUE TITLE
Legacy BootInstall Note

### ISSUE THREAD

**Issue by marz1970** [dortania/bugtracker#106]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

_* Guide(s) in question_
https://dortania.github.io/OpenCore-Post-Install/#how-to-follow-this-guide

_* Link to page(s) with the issue_
https://dortania.github.io/OpenCore-Post-Install/universal/oc2hdd.html#grabbing-opencore-off-the-usb

_* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)_
In the Special note to Legacy Users,  they are told not to forget to run the bootinstall.command.  However, If during the install, they are not prompted to change the EFI to MBR, the process has failed (Duh).  Users are informed they do not have permissions to alter the partition.

_* Include possible fixes_
SIP is left at enabled as default. Disabling SIP on the install media (USB), rebooting, and re-running the bootinstall.command has solved the problem for me.

**Comment by khronokernel** [comment]
Cannot replicate on our end, did you ensure you ran sudo before the command?
