### ISSUE TITLE
Big Sur release update

### ISSUE THREAD

**Issue by superkid200** [dortania/bugtracker#111]
Now Big Sur is released, however the OpenCore and macOS Big Sur page is still indicating that it's a beta.
And also, it may not make much sense to guide users through installing Big Sur at the moment. It has just been a week since it was released. So maybe also add a note to the Getting Started page?

Associated links:
[OpenCore and macOS 11: Big Sur](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur)

**Comment by khronokernel** [comment]
> It has just been a week since it was released. So maybe also add a note to the Getting Started page?

I agree, however Big Sur's launch has actually gone quite smoothly compared to last year for system stability so not *too* worried about users using the newer OS. Main things to warn are DRM and other userspace patches breaking

The other issue is the [OpenCore and macOS 11: Big Sur](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur) page you mentioned, as a lot of that info is covered in more detail on our [blog post](https://dortania.github.io/hackintosh/updates/2020/11/12/bigsur-new.html) and so I feel it would be best to heavily trim the page with very basic info(ie. dropped hardware, new SSDTs, etc) and have users read the longer post if they're interested
