### ISSUE TITLE
https://github.com/AMD-OSX/bugtracker pointing to https://github.com/acidanthera/bugtracker

### ISSUE THREAD

**Issue by andistern** [dortania/bugtracker#115]
https://github.com/AMD-OSX/bugtracker
contains 17h_19h, which is mentioned in https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-patch-issues
should perhaps be changed to point to https://github.com/dortania/bugtracker

**Comment by khronokernel** [comment]
A bit confused by your bug report, what's the error?

**Comment by khronokernel** [comment]
Realized your error, again we're not affiliated with AMD OSX. Please open an issue with them:
* https://github.com/AMD-OSX/bugtracker

**Comment by andistern** [comment]
link points to https://github.com/acidanthera/bugtracker (they do not support AMD ) instead of dortania/bugtracker ( or dit I get something wrong? )

**Comment by khronokernel** [comment]
We do not maintain OpenCore, all issues with the software should be directed to Acidanthera. We simply maintain documentation around using tools for hackintoshing
