### ISSUE TITLE
Arch key missing from AMD_Vanilla/17h_19h/patches.plist -> Kernel -> Patch

### ISSUE THREAD

**Issue by andistern** [dortania/bugtracker#116]
* Guide(s) in question
patches.plist, 
( cosmetic )
Line 254, 289 and more
* Link to page(s) with the issue
https://github.com/AMD-OSX/AMD_Vanilla/blob/opencore/17h_19h/patches.plist
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
accuracy / reliability of documentation ? 
* Include possible fixes
just insert appropriate lines _if applicable_, to show uniform appearance of patches:
```
				<key>Arch</key>
				<string>Any</string>
```
regards

**Comment by khronokernel** [comment]
Hi, this is Dortania and we are not affiliated with the AMD OSX organization. I believe you meant to open an issue at [AMD OSX](https://github.com/AMD-OSX/bugtracker)
