### ISSUE TITLE
[Comet Lake] Asus Z490-E and Intel I225-V 

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#117]
Hi there,
I've successfully installed macOS Big Sur 11.0.1 (20B29) on the following hardware:

- CPU: Intel Core i7-10700K
- GPU: Sapphire Pulse 5500XT 8GB
- MOBO: Asus ROG Strix Z490-E

I'm trying to enable the integrated NIC (Intel I225-V) without hope.
After looking in the IOReg the path of the controller and adding the device-id property, it still doesn't work.
Below a screenshot of IORegistryExplorer under `RP05`:

![image](https://user-images.githubusercontent.com/17933708/100119373-139d6480-2e77-11eb-926c-8e196f3a5e4c.png)

I'm seeing on the internet that many people still use FakePCIID... Do you think that this is totally wrong? 
Also, should I use IntelMausi, despite Apple provides a kext for I225-V controller?

Many thanks and have a nice day :")

**Comment by khronokernel** [comment]
I believe I see the issue, try using this properties:

```
device-id  |  Data  | F2150000
compatible | string | "pci8086,15f2"
```

> I'm seeing on the internet that many people still use FakePCIID... Do you think that this is totally wrong?

Not wrong, but not ideal imo. Wastes runtime and the kext is no longer maintained, better to use more stable solutions when applicable

> Also, should I use IntelMausi, despite Apple provides a kext for I225-V controller?

Mausi's kexts are based off the e1000e driver in Linux, while the i225v chipset is based off the i210 drivers. So they're actually incompatible

Please do report if this resolves your issue

**Comment by dreamwhite** [comment]
> I believe I see the issue, try using this properties:

Sadly, it's still not working:

![image](https://user-images.githubusercontent.com/17933708/100130003-83651c80-2e82-11eb-80ec-cc6882e9982d.png)

May I try by running a `kmutil showloaded | grep Intel`?

**Comment by khronokernel** [comment]
Add `msgbuf=1048576` to boot-args and then run this command:

```
sudo dmesg > ~/Desktop/dmesg.txt
```

Should tell us a bit more info where it's failing

**Comment by dreamwhite** [comment]
[dmesg.txt](https://github.com/dortania/bugtracker/files/5592444/dmesg.txt)


> Add `msgbuf=1048576` to boot-args and then run this command:
> 
> ```
> sudo dmesg > ~/Desktop/dmesg.txt
> ```
> 
> Should tell us a bit more info where it's failing

Sorry for the late reply. Here you are the dmesg log.
I've read it fastly and the only reference to `AppleIntelI210` is:

`AppleIntelI210::start - Built Aug 31 2020 22:05:31, fMapper 0`

Please let me know if you need any type of debugging files :")

**Comment by khronokernel** [comment]
```
DK: IOUserServer(com.apple.DriverKit-AppleEthernetE1000-0x1000002c2)::terminate(DriverKit_AppleEthernetE1000-0x1000002c2) server exit before start()
DK: DriverKit_AppleEthernetE1000-0x1000002c2::start(SL05-0x100000227) fail
```
Very odd, seems almost like a firmware issue. Looks very similar to Aquantia NICs failing

Is the board on the latest BIOS?

**Comment by dreamwhite** [comment]
> Is the board on the latest BIOS?

Yep, the board is on the latest BIOS version (0901)
Maybe we should try downgrading to other BIOS versions? (iirc there are only a few previous versions)

**Comment by khronokernel** [comment]
Hmm, have you tested with FakePCIID.kext before? If that works, might be able to compare the IOReg entries to see what properties are misaligned

**Comment by dreamwhite** [comment]
> Hmm, have you tested with FakePCIID.kext before? If that works, might be able to compare the IOReg entries to see what properties are misaligned

Alright, I'll make my tests and let you know if anything changes :") 

Stay tuned

**Comment by dreamwhite** [comment]
> > Hmm, have you tested with FakePCIID.kext before? If that works, might be able to compare the IOReg entries to see what properties are misaligned
> 
> Alright, I'll make my tests and let you know if anything changes :")
> 
> Stay tuned

I've tried flashing every BIOS version without any luck... The card isn't detected at all on macOS if I use 

> device-id  |  Data  | F2150000
> compatible | string | "pci8086,15f2"

At this point I'll try using FakePCIID, despite it's not recommended :/
