### ISSUE TITLE
SSDT-HPET: Where is oc_patches.plist?

### ISSUE THREAD

**Issue by palexdelisle** [dortania/bugtracker#118]
### Issue:
Here at 2 places you make reference to oc_patches.plist to merge into config.plist but this file is nowhere to be found:

[https://dortania.github.io/Getting-Started-With-ACPI/Universal/irq.html](https://dortania.github.io/Getting-Started-With-ACPI/Universal/irq.html)
[https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#adding-to-opencore](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#adding-to-opencore)

### Possible fix:
Put a link to the file

**Comment by khronokernel** [comment]
The file is generated by SSDTTime with the FixHPET option
