### ISSUE TITLE
Ice Lake high resolution screen flicker

### ISSUE THREAD

**Issue by PatrickH123** [dortania/bugtracker#119]
Hello there,

I have a Surface Pro 7 that has an i5-1035G4 with Intel Iris Plus Graphics G4. I'm able to boot into Catalina 10.15.7 without any kernel panics and graphics acceleration enabled, but the graphics only work well when the resolution is set to a not too high value. The default screen resolution is 2736x1824, but selecting this results in a lot of flickering. Setting it to 1368x912 for example solves this, but this is not preferred.

I am not sure whether this is a bug or a setting that is not correct in my setup. I cant seem to find the answer to this issue anywhere. All EFI folders that I have found have this issue and tell you to lower the resolution, but like that things do not look as sharp as they could.
[OC.zip](https://github.com/dortania/bugtracker/files/5603874/OC.zip)

Thank you for your time,

Patrick

**Comment by khronokernel** [comment]
Best to comment on this thread:
* https://github.com/dortania/bugtracker/issues/17
