### ISSUE TITLE
Ice Lake Laptop - AppleALC 1.5.4 causes system freeze

### ISSUE THREAD

**Issue by najeebanwer** [dortania/bugtracker#121]
Hi,
I have macOS 10.15.7 installed on a Dell XPS 13 9300 laptop and while most things appear to be working, I have not been able to get the audio to work. The specs for the system are:
CPU: Intel Core i7-1065G7 (Ice Lake)
GPU: Intel Iris Plus Graphics G7
RAM: 32GB
Disk: Samsung 970 EVO Plus 2TB NVMe SSD
Bootloader: OpenCore 0.6.3
SystemProductName: MacBookAir9,1

The audio codec for this system is ALC289. 
With AppleALC 1.5.3 (the previous version), I was able to boot the system using one of the existing layout ids (layout-id=11) and the internal speakers and microphone would show up in System Preferences, but there was no sound from the speakers.

On the insanelymac forum, user @fewtarius suggested that I try a patch that he had for the Controllers.plist file which had worked for other users of Ice Lake laptops. The patch did not work on my laptop; it caused the system to freeze with both the internal display and connected USB-C monitor showing a blank screen.

AppleALC 1.5.4 (the latest release) incorporates this patch to Controllers.plist and as a result my system freezes when I boot with this version of AppleALC and a valid layout id. If I boot with an invalid id (e.g. layout-id=13), the system boots fine but of course there is no audio.

I have added layout-id=12 to my version of AppleALC (1.5.5) and that causes a brief sound from the speakers right before the system freezes.

SInce the EFI folder is too large to attach to this post, I have put all relevant files in my OneDrive Public folder (link: https://1drv.ms/u/s!AnndH1latA6ZgTcYjAqOXJqzF69N?e=CDcdaK)

1. EFI - complete EFI folder
2. oc logs - All logs in the ESP partition root
3. Resources - My updates for ALC289, layout-id=12
4. system logs before - files from /var/log before trying any layouts that would cause the system to freeze
5. system logs after - files from /var/log after trying layout-id=11 (causes freeze with vanilla AppleALC 1.5.4) and layout-id=12 (causes freeze with my appleALC 1.5.5 after a brief sound from the speakers) and then finally setting layout-id=13 which allows system to boot, but no sound devices.
6. Dell XPS 13 9300 - codec0.txt - codec file from Linux

Any help with this issue is greatly appreciated. Thanks.

**Comment by fewtarius** [comment]
The issues tracker isn't for technical support.  There is some other problem with your machine or your configuration that you need to work out.
