### ISSUE TITLE
SMCSuperIO supporting Super IO controllers on AMD motherboards

### ISSUE THREAD

**Issue by TurannUl** [dortania/bugtracker#123]
![Ekran Resmi 2020-11-28 15 50 44](https://user-images.githubusercontent.com/70968210/100516478-3ab8a680-3195-11eb-9ece-75a469fd79e6.png)

**Comment by TurannUl** [comment]
![Ekran Resmi 2020-11-28 19 42 02](https://user-images.githubusercontent.com/70968210/100521347-2df77b00-31b4-11eb-9b1d-db3f24876df3.png)
Fan Read Works on AMD Based CPU

**Comment by khronokernel** [comment]
Hello, are you able to verify with other users that SuperIO in fact works and is stable on other machines? Main reason I ask is we've seen several times kernel panics resulting from usage of this kext, so would like to have a larger sample size before we update the guides

**Comment by TurannUl** [comment]
I was only able to experiment on 2 AMDs. I can't do any better. I just wanted to say you can choose not to update the Guide
