### ISSUE TITLE
[USB Mapping] POTx vs HSxx

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#128]
Hi there,
after doing some USB mapping using the manual USB Mapping method ([guide](https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html)), a doubt has arisen:

- on Intel platforms we usually define USB ports as `HSxx` (for USB 2.0) or `SSxx` (for USB 3.0).
- on AMD platforms there's no distinction in the naming of the ports, as they're called `POTx` (for both USB 2.0 and USB 3.0)

At this point should we define a guide line to follow like "for Intel use HSxx/SSxx" or the name doesn't matter? 
Many thanks in advance

**Comment by khronokernel** [comment]
Naming has no bearing, Apple used many names with their Nvidia based chipsets as they used EHCI, UHCI, OHCI, etc chipsets. Fun fact my MacBook7,1 has both POTx ports as well as HSxx ports. This is also why 3rd party USB controllers in a normal Mac Pro doesn't need to concern itself about a specific OS's naming convention

Hope this clears things up

**Comment by dreamwhite** [comment]
> Naming has no bearing, Apple used many names with their Nvidia based chipsets as they used EHCI, UHCI, OHCI, etc chipsets. Fun fact my MacBook7,1 has both POTx ports as well as HSxx ports. This is also why 3rd party USB controllers in a normal Mac Pro doesn't need to concern itself about a specific OS's naming convention
> 
> Hope this clears things up

Many thanks for the clarifications ^^
I'm using `HSxx/SSxx` naming convention since it's more readable than `POTx`. (e.g. if `SS01` exists, I'm sure that `HS01` will exist too)
