### ISSUE TITLE
framebuffer-patch-enable property makes UHD 630 not output 4k

### ISSUE THREAD

**Issue by Digmin3** [dortania/bugtracker#130]
Following [Intel Desktop config.plist -> Coffee Lake -> DeviceProperties guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#add-2) tells you to enable framebuffer-patch-enable property.

However (in my case) using this property prevents 4k resolution appear on screen settings.
Fix: setting framebuffer-patch-enable to 00000000
I found this solution at [Reddit](https://www.reddit.com/r/hackintosh/comments/euad2q/uhd_630_not_outputting_4k/?utm_source=amp&utm_medium=&utm_content=post_body).

My CPU is Intel i7-8700k which uses the UHD 630 iGPU and I don't have dGPU.

It will be nice to add a note about this property at the guide, because in some builds like mine cause trouble (Still boots but with non-optimal resolution).

**Comment by Digmin3** [comment]
My bad, thought the last sentence only refers to framebuffer-stolenmem 

Thanks for fast response, suggestions aside the guide is incredible, you've done a great job.

**Comment by khronokernel** [comment]
Forgot to close earlier: https://github.com/dortania/OpenCore-Install-Guide/commit/3c5cdbed8bb639bc4e9b7461e27e2cc39caf2023
