### ISSUE TITLE
Sleep issue on AMD

### ISSUE THREAD

**Issue by xlofhappy** [dortania/bugtracker#131]
I don't know if it's the right place to paste my issue.
I followed the guides [install, post-install], anything works well but sleep.
so, I followed the Post guides [fix sleep] again and again.
1. usb-map corrected
2. no dGPU (3900x + ASUS X570 + RX 470)
3. no Thunderbolt
4. NVMe fix
5. AMD CPU PowerManagement added and works well
when I click sleep on the apple menu, the monitor turned off, but the use still on power, the cpu still running and can't wake up

I don't think I did wrong configuration, I had no idea to try and way to find the real reason and fix it,
so I think if it's a new problem not listed in the guide, I need some points to find out the culprit

**Comment by xlofhappy** [comment]
[Uploading EFI.zip…]()

**Comment by xlofhappy** [comment]
[EFI.zip](https://github.com/dortania/bugtracker/files/5722790/EFI.zip)

**Comment by xlofhappy** [comment]
I upgrade to Big sur without any error, and the  sleep issue disappears.

**Comment by dreamwhite** [comment]
> I upgrade to Big sur without any error, and the sleep issue disappears.

May I ask you what's your current hibernatemode status?

**Comment by xlofhappy** [comment]
> > I upgrade to Big sur without any error, and the sleep issue disappears.
> 
> May I ask you what's your current hibernatemode status?

Zero

**Comment by PMheart** [comment]
Hello! Please use forums for support.
