### ISSUE TITLE
Opencore-Multiboot webpage not available on dortania.github.io

### ISSUE THREAD

**Issue by DestroyerXyz** [dortania/bugtracker#134]
Please stop and read this carefully. Otherwise, your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

* Guide(s) in question
OpenCore-Multiboot
* Link to page(s) with the issue
https://dortania.github.io/OpenCore-Multiboot
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
There is a 404 error
* Include possible fixes
  * Depending on the complexity of the fix, sources may be required
  
Note we only maintain Dortania guides, so please do not open issues for other guides.

**Comment by khronokernel** [comment]
Multiboot guide is currently a work in progress and is not meant to be used by end users. Reason we have zero references to the site in any other guide. We will add it when we feel it's complete, currently all our members are quite busy with bigger projects so the Multiboot guide has been put on hold
