### ISSUE TITLE
Spelling Error in Terminal Commands in Fixing MacPro7,1 Memory Errors

### ISSUE THREAD

**Issue by perez987** [dortania/bugtracker#135]
The Fixing MacPro7,1 Memory Errors guide shows fragments of _bash_ code with the _dmidecode_ command, in all of them it shows _dmidecode -t memory_ joined to _grep_ to find a specific string that is the memory property whose value we want to know.
The search string must be enclosed in quotes but in all the code boxes there is an **extra space** after the first quotes, if _dmidecode_ is executed like this, no result is obtained, you have to remove that extra space so that _grep_ works well and returns the value of the searched property.
The guide is here:
https://dortania.github.io/OpenCore-Post-Install/universal/memory.html
This is an example:
![grep](https://user-images.githubusercontent.com/50429399/103242662-5ca17680-4957-11eb-975d-d50eefae8bd6.png)

Congratulations everyone for your work!!! Thank you!!!

**Comment by khronokernel** [comment]
Hrrmm so I tried to have a tab instead of a space, didn't realize markdown will just interpret a tab as a space and broke my logic.

Thanks for pointing this out! Will resolve shortly
