### ISSUE TITLE
No mention of Intel 11th Gen Mobile (Tiger Lake) in the guides

### ISSUE THREAD

**Issue by DestroyerXyz** [dortania/bugtracker#136]
* Guide(s) in question
OpenCore-Install-Guide, Getting-Started-With-ACPI
* Link to page(s) with the issue
https://dortania.github.io/OpenCore-Install-Guide/ktext.html#ssdts , https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#laptop
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
No mention anywhere about Tiger Lake (not even a "Does not work")

**Comment by khronokernel** [comment]
We have zero reports of Tiger Lake, so unfortunately cannot comment on success or not. GPU drivers are missing, so no acceleration as mentioned here: [Intel GPU Support Chart](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#gpu-support)

Additionally, macOS's kernel hasn't added Tiger Lake support last we checked so will need a Fake CPUID. However as we have no reports, we cannot confirm which Fake IDs work best.

If you have threads discussing the success of these laptop, we're more than happy to add information to dortania. However as it stands, we don't have enough information to neither confirm nor deny support(CPU wise)

**Comment by DestroyerXyz** [comment]
@khronokernel Can you atleast say that it is not tested yet, in the guides?

**Comment by djdeniro** [comment]
check it [ux482ea](https://github.com/deniro98/hackintosh-asus-zenbook-duo-ux482ea)

Tiger Lake
