### ISSUE TITLE
[Broken link] getting started with ACPI > Fixing Backlight:manual > dsl

### ISSUE THREAD

**Issue by Overc1ocker** [dortania/bugtracker#137]
Hello! I just wanted to report these broken links before they cause anyone any trouble. In the getting started with acpi guide in the fixing backlight: manual section, attempting to download a DSL results in a 404 error. Please fix!

Guide in question:  
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/backlight-methods/manual.html#edits-to-the-sample-ssdt

Thank you so much for these amazing guides! Have a nice 2021

**Comment by khronokernel** [comment]
Oh yes thank you for mentioning this! I meant to fix the links when a few of the SSDTs were moved, we fix this shortly

**Comment by Overc1ocker** [comment]
Awesome! Thank you!
