### ISSUE TITLE
[Request] Specify that multiple HP machines may require SSDT-RTC0 if stuck at [PCI configuration end]

### ISSUE THREAD

**Issue by Overc1ocker** [dortania/bugtracker#138]
Hello! I have spent a little while trying and successfully installing macOS on my HP 15-DA0014dx. It is a mid-range Kaby lake -r laptop from 2018. My first boot hangup was the infamous [PCI configuration end] issue. After hours of digging, I found that just like the HP 250 G6, a drunk programmer wrote my DSDT and provided no easy way to enable the RTC. I have since seen other members of the community having the same issues with HP laptops. Is it possible we can state this in the guide? Maybe like this: 

Some drunk firmware writers at HP seem to have disabled the RTC on some of their laptops with no way to actually re-enable them. A famous example is the HP 250 G6 . For users cursed with such hardware you'll need to create a fake RTC clock for macOS to play with. See getting started with ACPI for more details.

Link to the guide i'm requesting the addition to.

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-rtc-pci-configuration-begins-previous-shutdown-hpet-hid-legacy

**Comment by khronokernel** [comment]
Added to 0.6.5 branch, we'll be merging tomorrow so just easier than messing with merge conflicts. Thanks for the issue!
