### ISSUE TITLE
Add MSI Navi note

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#14]
As of writing, there are still issues with MSI's Navi line in Catalina's installer. Will need to add this line to the [What GPUs to avoid](https://dortania.github.io/GPU-Buyers-Guide/buyers-guide/gpu-avoid.html) as to help steer users away from them until Apple resolves the issue

Resources:

* https://github.com/acidanthera/bugtracker/issues/901

**Comment by 1Revenger1** [comment]
Maybe the debugging steps should be added to the troubleshooting page in addition to steering them away

**Comment by khronokernel** [comment]
Added info here:
https://github.com/dortania/OpenCore-Desktop-Guide/pull/86
https://github.com/dortania/GPU-Buyers-Guide/commit/be10d12184abb840fac6d5df96d3109f305ef5e8
