### ISSUE TITLE
Software DRM decoding removed in Big Sur

### ISSUE THREAD

**Issue by dhinakg** [dortania/bugtracker#141]
Probably best to put a small note

**Comment by dreamwhite** [comment]
What's the purpose of this issue? I don't see any proof of that. Please attach them if you have it

**Comment by dhinakg** [comment]
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md#drm-compatibility-on-macos-11

**Comment by PMheart** [comment]
Assuming resolved.
