### ISSUE TITLE
ACPI Error booting the installer

### ISSUE THREAD

**Issue by josemmc95** [dortania/bugtracker#142]
I followed the guide and I can't boot.

Here I leave my EFI folder and the log. I've deleted kext and resources folder to be able to upload the file here. All kexts are updated to latest version.

I don't know what's happening.

Thank you in advanced.

![RenderedImage](https://user-images.githubusercontent.com/62221854/104190576-92952f00-541c-11eb-8d23-0a99f5b5acbb.jpg)

[EFI.zip](https://github.com/dortania/bugtracker/files/5796100/EFI.zip)

**Comment by khronokernel** [comment]
Little hardware info provided, closing till more details added

**Comment by josemmc95** [comment]
Sorry, I forgot to add the details.

It's a Huawei Matebook D 14".

i5-10210U
Intel Graphics 620

Here I leave you the HWInfo Report and DSDT dump.

Thank you in advanced.
[info.zip](https://github.com/dortania/bugtracker/files/5901118/info.zip)

**Comment by josemmc95** [comment]
Updated to OC 0.6.6 and still have the same problem
