### ISSUE TITLE
Wifi Kext Issues 

### ISSUE THREAD

**Issue by hellisabove** [dortania/bugtracker#143]
Followed the guide and efi boots but if I install the kexts for my wifi card for catalina the usb only boots to menu and if I go to install macOS, it spits some text and then says "OCB: StartImage failed - Aborted"

log file: https://www.mediafire.com/file/6rx5vcv97ehphvm/opencore-2021-01-12-115321.txt/file
efi: https://www.mediafire.com/file/d8cp0w7rf6elb04/efi.zip/file

**Comment by khronokernel** [comment]
Little hardware info provided, closing till more details added
