### ISSUE TITLE
config.plist lacks device-id for Intel UHD Graphics 630

### ISSUE THREAD

**Issue by egzumer** [dortania/bugtracker#144]
Processor: i9-10850K
Opencore: 0.6.5
macOS: 10.15.7

The issue was that Mozilla thunderbird was crashing with: 
`Assertion failed: (0), function CreateCompiler, file /Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-14.7.8/GLRenderer/kbl/usc_interface.cpp, line 1676.`

Also Hackintool on system tab in IGPU section was showing unknown graphic.
Adding `DeviceProperties->PciRoot(0x0)/Pci(0x2,0x0)->device-id -> 983E0000` fixed the issue

see also: https://github.com/alacritty/alacritty/issues/4375

**Comment by dreamwhite** [comment]
Uhm, despite macOS Catalina should be compatible with Comet Lake CPUs, Big Sur grants the full compatibility :/
Also, I don't see your motherboard model, so I can expect that your iGPU patch is wrong :/

**Comment by khronokernel** [comment]
So I just verified, the 10850K iGPU's Device ID is 0x9BC5. This ID is present in macOS Catalina, so your issue is more likely else where. The device ID you listed above is for Coffee Lake, which is not ideal for Comet Lake hardware in supported OSes.

**Comment by khronokernel** [comment]
Will add some info to troubleshooting page as a work around until this is diagnosed further
