### ISSUE TITLE
Big Sur 11.1 in Pentium dual core g3240 with Nvidia gt 710

### ISSUE THREAD

**Issue by vinukn335** [dortania/bugtracker#145]
I am facing kernel panic while clean installing Big Sur 11.1 on Intel Pentium dual core g3240 with NVidia gt 710.(I know it is not supported, Catalina works well!)
oc latest

AMFI: SIP is off, allowing core dump for pid 1 (launchid)
pid 1 exited -- exit reason namespace 2 subcode 0x4, description none

IOPlatformPanicAction -> AppleAHCIDiskDriver
IOPlatformPanicAction -> AppleAHCIDiskDriver
IOPlatformPanicAction -> AppleSMC

panic(cpu 1 caller 0xffffff8006cbf016):initproc exited -- exit reason namespace 2 subcode 0x4 

![IMG20210111200301 thumb jpg ac4811f01c6134a9722ae5d57b9ad980](https://user-images.githubusercontent.com/47185599/106361051-d99e8200-6341-11eb-8f8a-d5fe793de94b.jpg)

EFI
[EFI.zip](https://github.com/dortania/bugtracker/files/5898241/EFI.zip)

**Comment by PMheart** [comment]
Hello! Please use forums for support.
