### ISSUE TITLE
Ivy Bridge-E CPU don't support xcpm natively

### ISSUE THREAD

**Issue by BrushXue** [dortania/bugtracker#146]
This is a follow up of https://github.com/dortania/bugtracker/issues/48. The processor ID issue is resolved. Now I can boot into the system with OC 0.6.6

From this page
https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#enabling-x86platformplugin
> Note: Ivy Bridge-E CPUs do officially support XCPM

My CPU is dual E5-2667 v2 and motherboard is C602. I should be able to activate xpcm. However it's not true in my case. 
If I use `SSDT-PLUG.aml`, I'll get the following result:
```
X86PlatformPlugin::getCPUCStates - Unexpected data for C1
X86PlatformPlugin::getCPUPStates - C000 APSS and _PSS evaluations failed
X86PlatformPlugin::getCPUPStates - acpiPSArrayObj is not an valid OSArray
X86PlatformPlugin::publishAPICStates - Failed to get CPU P States!
X86PlatformPlugin::publishAPICStates - Failed to get max non-turbo PState. Set max non-turbo PState to default value 1
```
If I use ssdtPRGen, CPU power management will be available (X86PlatformPlugin is correctly loaded). But the frequency is always high (3.3GHz~4.0GHz) and never reach down to 1.2GHz.

**Comment by khronokernel** [comment]
> Note: Ivy Bridge-E CPUs do officially support XCPM

Yeah this is actually incorrect on our part, Apple dropped Ivy Bridge E support with El Capitan and newer. So Mavericks and Yosemite would be the only OSes to support your hardware with XCPM.

Regarding ssdtPRGen creating unideal frequencies, that would need to be investigated further on your end. Acidanthera has an XCPM project for unsupported hardware, however we're unsure if this will ever be finished and released to the general public. I would say keep an eye out a few months from now and see if there's anything new in the world of XCPM

I'll leave this issue open, as I have been meaning to correct the XCPM info earlier in the guides

**Comment by BrushXue** [comment]
Thanks. It that's the case, my transition from Clover to OpenCore is finally finished!

**Comment by BrushXue** [comment]
After some research, there's a BIOS option called **P States Coordination**
Changing it from **HW_ALL** to **SW_ALL** resolves the high freq issue. Previous when idling it's floating between 3.3GHz~4.0GHz. Now it can drop to 1.2GHz. Please add this to HEDT config tutorial as a note.
![Screen Shot 2021-02-08 at 10 55 02 PM](https://user-images.githubusercontent.com/12702149/107313653-00a33500-6a61-11eb-9905-e7d6ee570e85.png)
