### ISSUE TITLE
[OpenCore Sanity Checker] Possible conflict with OpenHfsPlus

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#148]
Hi there,
I apologize if this isn't the right place where to report this issue, but that's the only way I found to reach you.
Starting from OpenCore 0.6.6, users can replace `HfsPlus.efi` driver with `OpenHfsPlus.efi`, which has the same functionality: allow the bootloader to scan HFS+ (Extended MacOS Journaled) partitions. However, the driver is still in development stage, and the detection process is slow, if compared to the other driver.

Anyways, if a user uses `OpenHfsPlus.efi` driver instead of `HfsPlus.efi`, the sanity checker raises an error as depicted on the below screenshot:

![image](https://user-images.githubusercontent.com/17933708/107547095-601e5380-6bcd-11eb-90af-1cd3c7776431.png)

Should this "error" be changed into a "warning" that suggests the user to use `HfsPlus.efi` for better detection speed?
Thanks for eventual clarifications, and have a nice day ^^
dreamwhite

**Comment by DMNerd** [comment]
OpenHfsPlus.efi should be definitelly encouraged instead of VBoxHfs from now on

**Comment by khronokernel** [comment]
Forgot to close this issue:
https://github.com/rlerdorf/OCSanity/commit/8a025c5a075a3a9304c5cf5c7b32cb4e596b9c89
