### ISSUE TITLE
[OpenCore For Legacy Mac] add iMac11,3 sound support with ALC

### ISSUE THREAD

**Issue by Ausdauersportler** [dortania/bugtracker#149]
Opening this issue on your request as shown on this page:

https://dortania.github.io/OpenCore-For-Legacy-Macs/post-install/audio.html

Added output of `ioreg -lw0` created on Sierra (macOS 10.12) which is still supported in this machine.

[ioreg.txt](https://github.com/dortania/bugtracker/files/5970270/ioreg.txt)

**Comment by tiziodcaio** [comment]
Use this bugtracker https://github.com/dortania/OpenCore-Legacy-Patcher/issues
