### ISSUE TITLE
Emulated NVRAM on H67 Sandy Bridge Bless not working

### ISSUE THREAD

**Issue by brunogermain** [dortania/bugtracker#151]
Hello everyone,
I hope this is the right place to ask...

I recently gave new life to an old Asus P8H67-M EVO mobo. Installed High Sierra (APFS) on a new SSD alongside the old SSD running Mountain Lion (HFS+). Both systems work perfectly (PM, sleep, shutdown, restart) booting with Opencore 0.6.5 DuetPkg

The only thing I cannot get to work is telling OpenCore to boot the High Sierra drive by default.

After enabling emulated NVRAM, I made many experiments, all to no avail. The system keeps defaulting from the Mountain Lion SSD.
The configuration that's apparently giving less errors in the boot log is the one attached, which has OpenRunTime.efi disabled.

Now the question is: am I doing something wrong, or this mobo simply  doesn't support BootOrder and BootNext?

EFI folder, nvram.plist and OpenCore boot log attached
[Asus_P8H67-M_debug.zip](https://github.com/dortania/bugtracker/files/5981805/Asus_P8H67-M_debug.zip)

**Comment by PMheart** [comment]
Hello! Please use forums for support.
