### ISSUE TITLE
[OpenCore For Legacy Macs] Add iMac8,1 20" support to AppleALC

### ISSUE THREAD

**Issue by educovas** [dortania/bugtracker#153]
ioreg.txt from 'ioreg -lw0' created on 10.11.6 which is the latest supported by the iMac8,1.

[ioreg.txt](https://github.com/dortania/bugtracker/files/5991916/ioreg.txt)

**Comment by tiziodcaio** [comment]
try using this bug tracker https://github.com/dortania/OpenCore-Legacy-Patcher/issues
