### ISSUE TITLE
Add ocvalidate support to Post Install Guide

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#159]
Ref: [Updating OpenCore and macOS](https://dortania.github.io/OpenCore-Post-Install/universal/update.html)

**Comment by dreamwhite** [comment]
@khronokernel I just wrote a draft on a few sheets of paper and came to the conclusion that probably to mention `ocvalidate` we have two choices:

1. Edit Line 52 of [update.md](https://github.com/dortania/OpenCore-Post-Install/blob/master/universal/update.md) as it follows:
```
Once you've made the adjustments and made sure you config is compliant with the newest release of OpenCore using `ocvalidate` OpenCore utility, make sure to double check your setting with the OpenCore Guide on what to set everything to, otherwise read the Differences.pdf if you want to get a bit more technical.
```

2. Write a new paragraph called `Check config.plist integrity` or something similar where we can provide more informations like images of ocvalidate.

Please let me know what you think about that and what's your preferred choice so in the next days I can try to write off one of those ideas.
Have a nice day
dreamwhite

**Comment by khronokernel** [comment]
Hmm I'm kinda leaning towards #2 as new users will be unfamiliar with ocvalidate. Perhaps as you mentioned, we can add a brief intro, how to use and images of what it should look like

**Comment by dreamwhite** [comment]
> Hmm I'm kinda leaning towards #2 as new users will be unfamiliar with ocvalidate. Perhaps as you mentioned, we can add a brief intro, how to use and images of what it should look like

Alright, how should we proceed then? Would you like that I provide a screenshot of `ocvalidate`? If so, which terminal should I use? I see that in dortania's guides Terminal.app is used. Do you care about it or can I provide the screenshots using iTerm2?

I attach a screenshot of how a mine would be like:

![image](https://user-images.githubusercontent.com/17933708/108636429-6fcb5100-7485-11eb-8c7a-91c33d606b10.png)

Eventually I can clear the console:

![image](https://user-images.githubusercontent.com/17933708/108636447-912c3d00-7485-11eb-8090-e02744082121.png)

**Comment by khronokernel** [comment]
> Would you like that I provide a screenshot of ocvalidate? If so, which terminal should I use? I see that in dortania's guides Terminal.app is used. Do you care about it or can I provide the screenshots using iTerm2?

To keep consistency I can handle the screenshots. If you want, you can add placeholder images that I can later replace

**Comment by dreamwhite** [comment]
@khronokernel I just wrote a draft of the update.md file. Please let me know if you need more infos, despite ocvalidate is self-explanatory :/

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Post-Install/pull/53
