### ISSUE TITLE
[Typo list] Booter/Quirks

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#160]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

* Guide(s) in question: 

Desktop config.plist
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/clarkdale.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/penryn.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/sandy-bridge.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/ivy-bridge.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake-bridge.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#booter

Laptop config.plist
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/arrandale.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/sandy-bridge.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/ivy-bridge.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/haswell.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/broadwell.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/skylake.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#booter
- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/icelake.html#booter

* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)

* Include possible fixes

- ProvideCustomSlide: YES

    - Used for Slide variable calculation. However the necessity of this quirk is determined by `OCABC: Only N/256 slide values are usable!` message in the debug log. If the message `OCABC: All slides are usable! You can disable ProvideCustomSlide!` is present in your log, you can **disable** ProvideCustomSlide.

Replace **disabled** with **disable**

**Comment by dreamwhite** [comment]
@khronokernel please note that I updated the comment by mentioning also AMD config.plist.
Despite AMD motherboards are known to have weird memory layouts, some of them may require to disable `ProvideCustomSlide`.

**Comment by khronokernel** [comment]
Ah thank you, yeah added it here: https://github.com/dortania/OpenCore-Install-Guide/commit/0e9fb53efb6e4a1781991012ef15b6500c0c00f6
