### ISSUE TITLE
XhciPortLimit Issues Thread

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#162]
As mentioned here: 
* [XhciPortLimit broken in macOS 11.3 Beta 2(20E5186d)](https://github.com/acidanthera/bugtracker/issues/1514)

XhciPortLimit patch will result in unbootable machines, and so will need to find work arounds or new patches to resolve this situation. This issue is to help notify users and developers.

Regarding Dortania:

Since we expect either GM or proper release of 11.3 to the public next week, our guides will need to be updated accordingly:
* [ ] Add note to config pages about XhciPortLimit no longer functioning correctly in macOS 11.3+
* [ ] Recommend users install macOS 11.2 or older to work around XHCI issues if you cannot install
  * As majority of users rely on the macrecovery.py installation method, we'll need to recommend users to run macOS 10.15 or older
  * Additionally we could attempt to host recovery images for education purposes, recommend users create a USB map and then update to newer OSes
    * This relies on Apple still hosting 11.2 install images for recovery, will need to monitor closely
    * [Archive Link](https://archive.org/details/base-system_202102)
* [ ] Mention using a USB 2.0 drive or 3rd party XHCI controllers such as the AsMedia series which commonly stay under the 15 port limit

**Comment by khronokernel** [comment]
Resolved with macOS 11.3 Beta 3

**Comment by romanolicker** [comment]
Is this still broken? I was unable to boot and start the installer with 11.4.
What are the next steps here? Any idea when an update is expected?

**Comment by fisforfaheem** [comment]
it it fixed??? i am on lenovo x230

**Comment by lukaz-m** [comment]
Following, is this still a present issue with 11.5.1?

**Comment by dreamwhite** [comment]
> Following, is this still a present issue with 11.5.1?

"""Sadly""" yes but there's no need to worry about honestly. Despite the number of USB ports on your machine, is way safer trying to stay under the 15 port limit and map first the USB2 ports, then the USB3.
I don't know if XhciPortLimit is the reason why many ASUS Z490 boards have USB problems, but apparently without it there's even no need of using SSDT-RHUB :)

**Comment by OnlyIslam** [comment]
it it fixed?  Is this still broken?

**Comment by 19ojones** [comment]
Still doesn't seem to work. Anyone got any ideas?

**Comment by dreamwhite** [comment]
> Still doesn't seem to work. Anyone got any ideas?

Still don't get why in 2023 people still use such quirk, despite it's labeled as unstable and can potentially lead to crashes/undefined behaviour...

**Comment by 1ryuken** [comment]
keyboard and launchpad not starting ? in 11 dose tiger lake support ?

**Comment by Bushboom77** [comment]
I have 2 ports, do I need to do anything?
