### ISSUE TITLE
Suggestion: allow config to require only non-default values

### ISSUE THREAD

**Issue by joncas** [dortania/bugtracker#174]
Hello,

I know your policy is not to have any default values and require all options to be listed in config.plist, but this means that with every update one has to discover the new options to add them to the config.

It would greatly simplify the upgrade process if all default options could be omitted in config.plist, such that one only needs to keep those with non-default values which usually don't change from one version to the next.

Only a suggestion ! :-)

**Comment by khronokernel** [comment]
This would break OpenCore's spec, we do not support configurations that do not conform to the Bootloader's expected setup
