### ISSUE TITLE
Broken link to Linux iasl executable.

### ISSUE THREAD

**Issue by naim5am** [dortania/bugtracker#178]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:
In [Linux Compiling and Decompiling](https://dortania.github.io/Getting-Started-With-ACPI/Manual/compile.html#linux) the
link http://amdosx.kellynet.nl/iasl.zip to iasl build is broken, can it be hosted elsewhere? 
regards

**Comment by dreamwhite** [comment]
To be fair you could opt for downloading iasl for linux by installing `acpica-tools` package (I tested it on Pop!_OS and Ubuntu and it works).
Please let me know if you manage to solve it

**Comment by naim5am** [comment]
Yes solved. I actually forgot that's how I solved it a week ago.

**Comment by PMheart** [comment]
Closing as resolved.
