### ISSUE TITLE
Embedded Control - Renaming vs Add SSDT

### ISSUE THREAD

**Issue by rottenpants466** [dortania/bugtracker#18]
Since there was a change in the guide about patching the EC i wanted to report that, at least for me, removing the EC rename and adding the SSDT-EC-USBX-LAPTOP messes up my battery. 

To be exact, after applying the ssdt the laptop's charging light is always orange while in macOS it says is 100% charged. Yesterday after watching a movie when I unplugged both the ac and hdmi cables the laptop suddenly turned off and it didn't turn on again. I pressed the power button like 100 times but nothing, the laptop was "dead". I inserted back the ac cable and the charging light didn't turn on.... I thought that either the battery died or there was a problem with the ac adaptor but nope.

After that I opened the laptop, removed and inserted the battery again and it finally turned on. After booting up I checked the battery level and it was 98% so I really don't know what happened...

Obviously I reverted back to renaming my EC device and removed the SSDT-EC-USBX-LAPTOP. After that when the laptop reaches 100% the charging light turns white like before.

In terms of battery patches I don't thing this laptop needs any since almost all of the items in the ECF2 field in the DSDT are 8bit or less. There are a couple of 16bit items there but none of them are accessed in the rest of the DSDT. Mutex objects also return 0 so no need to patch that as well.

Im not asking for help with this problem, just want to give a heads up and that this might happen to other people as well.

Im leaving here my DSDT and EFI folder in case someone wants to take a look at it. (Removed stuff in platform info and deleted stuff in the resources folder to save space)

HP Pavilion 14-bf104np
I7 8550u (kabylake r)
UHD620 + Nvidia 940mx (disabled)
Wifi/Bt DW1560

cheers

[EFI+DSDT.zip](https://github.com/dortania/Getting-Started-With-ACPI/files/4618378/EFI%2BDSDT.zip)

**Comment by khronokernel** [comment]
Gonna close this issue for now, if others encounter the same I'll reopen but for now I feel this isn't a major issue
