### ISSUE TITLE
Coffee Lake i7-8750H UHD630 issue with new version of WhateverGreen

### ISSUE THREAD

**Issue by naufalkharits** [dortania/bugtracker#182]
I haven't update the kext since i built EFI with OpenCore 0.6.3 (evereything is normal & perfect,
and today i do update with the latest kext.

I got black screen after Apple Logo, but i believe & sure the system boot work to Mac Login (when I increas-decrease brightness the feedback "boop")

---

Problem solve:
need to add boot-args: -igfxblr
need to add property: enable-backlight-registers-fix

---

I think you may need put of my problem solve to the Dortania's web guide as optional thing need to do.
just in case for others experience something similar

---

thx,
sorry for bad english

**Comment by PMheart** [comment]
Assuming this has been resolved. If not, please reopen this issue.
