### ISSUE TITLE
AppleALC resources failed

### ISSUE THREAD

**Issue by Vepoe** [dortania/bugtracker#184]
I use the AppleALC.xcodeproj of AppleALC-master-v1.5.8 to resources a drive for Alc897 of Gigabyte_b560m_aorus_pro.
Then there has a error.
![截屏2021-04-02 下午4 14 25](https://user-images.githubusercontent.com/58576156/113402411-885d4e00-93d7-11eb-8977-69f4a482bc6b.png)
@vit9696

**Comment by dhinakg** [comment]
We do not provide build support here
