### ISSUE TITLE
Unable to boot Without USB EFI on legacy system

### ISSUE THREAD

**Issue by tapanmazumder** [dortania/bugtracker#187]
Opencore can’t boot without USB Drive.

I have successfully install Mac OS High Sierra on my Dell Vostro 1450 (Sandy Bridge). But unfortunately it’s an legacy system so I run duet package on Main Hard Disk too still my bios is not able to detect the opencore bootloader from hdd. It shows only when the usb drive is plugged in.  Any help ??

Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

* Only the latest released versions of OpenCore, Lilu, and other KEXTs are supported.
* Bug reports involving Chameleon, Clover, Ozmozis or alike are not accepted.
* Include your `EFI` directory with OpenCore.
* Include OpenCore DEBUG log (refer to `Target` in [Configuration.pdf](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) or here: [OpenCore Debugging](https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/debug.html)).
* Include Lilu DEBUG log (refer to `-liludbgall liludump=60` boot arguments in Lilu's [README](https://github.com/acidanthera/Lilu/blob/master/README.md)).

When to use [Acidanthera's issue tracker](https://github.com/acidanthera/bugtracker):

* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs and believe it is not a configuration issue
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 or higher to avoid kext names scrolling over the panic log you should also set `PanicNoKextDump=YES` in OpenCore. Use `ApplePanic=YES` to write a kernel panic log to file._

**Comment by tiziodcaio** [comment]
Have you copied OC to the hard disk???

**Comment by tapanmazumder** [comment]
> Have you copied OC to the hard disk???

Yes.

**Comment by PMheart** [comment]
Hello! Please use forums for support.
