### ISSUE TITLE
Wait at prelinkedkernel for 5 minutes?

### ISSUE THREAD

**Issue by chenmin1992** [dortania/bugtracker#188]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

* Guide(s) in question
   Making the installer in Windows
* Link to page(s) with the issue
  https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
  Maybe it's not a issue, but it wates time.
  behavior: 
  follow this guide to make macos installer in windows, but it wait at prelinkedkernel about 5 minutes, see the screenshot below, after 5 minutes, it will go on boot process, and can boot into macos installer, I wonder is it normal? does it behavior correctly? if it was a mistake, how to deal with it?
![image](https://user-images.githubusercontent.com/20168118/113673166-370cd180-96eb-11eb-8460-364b4b356f5f.png)

* Include possible fixes
  I have no idea, I found this QA https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-ld-ofs-err-0xe-when-booting-preboot-volume , but it can boot into macos installer, so this is not that QA.
  
Note we only maintain Dortania guides, so please do not open issues for other guides.

**Comment by dhinakg** [comment]
Buggy USB implementation or slow USB, nothing you can do about it
