### ISSUE TITLE
Incorrect version of OpenCore in NVRAM

### ISSUE THREAD

**Issue by najeebanwer** [dortania/bugtracker#189]
I am using OpenCore 0.6.8. According to the OpenCore Install Guide, this command shows the version of OpenCore in use.
![image](https://user-images.githubusercontent.com/34123660/113942113-efa74380-97c5-11eb-9b27-a16b2c767788.png)

This is what I see when I use this command.
![image](https://user-images.githubusercontent.com/34123660/113942217-16fe1080-97c6-11eb-8593-368fcf60d419.png)

**Comment by khronokernel** [comment]
Reset NVRAM, bug was resolved in 0.6.7

**Comment by najeebanwer** [comment]
Okay, I reset NVRAM and this is the result.
![Screen Shot 2021-04-07 at 5 35 38 PM](https://user-images.githubusercontent.com/34123660/113943152-b1ab1f00-97c7-11eb-8f49-90416c793d21.png)

**Comment by khronokernel** [comment]
Regardless, the command is still valid. Open an issue in Acidanthera's bug tracker if you feel this is an actual bug with OpenCore. Dortania simply write documentation, we're not responsible for the code of OpenCorePkg

**Comment by najeebanwer** [comment]
Ok, my mistake; I thought this was the OpenCore bug tracker. It's confusing since there seems to be quite a bit of discussion about OpenCore issues on this forum.
