### ISSUE TITLE
Issues with Lenovo 320-15AST

### ISSUE THREAD

**Issue by G3NSVRV** [dortania/bugtracker#191]
I'm encountering some issues installing macOS Catalina on the Lenovo Ideapad 320-15AST which is an amd cpu/gpu.

I've followed all the steps mentioned on the opencore install guide from dortania, then I followed up the specific instructions for amd systems, particularly for my system which is an a9-9420 (16h).

After a couple of configurations and kexts, I got on the step where the LID is not being recognized, and sincerely Idk what to do now, if I need a kext file, which one, maybe tweak my system...

I'm using a dump aml from my current system, I gattered using the python script on linux.

The message is the following, after this the laptop got frozen forever:
![image](https://user-images.githubusercontent.com/11720535/114247658-9ffe7e80-9963-11eb-9aa5-31572744e94f.png)

[opencore-2021-04-09-222034.txt](https://github.com/dortania/bugtracker/files/6288786/opencore-2021-04-09-222034.txt)
[tree.log](https://github.com/dortania/bugtracker/files/6288787/tree.log)

**Comment by dhinakg** [comment]
AMD laptops are not supported, did you read the guide?
