### ISSUE TITLE
No Audio on Conexant

### ISSUE THREAD

**Issue by tapanmazumder** [dortania/bugtracker#197]
No audio layout for Conexant CX20671-21Z

 stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

* Guide(s) in question
* Link to page(s) with the issue
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
* Include possible fixes
  * Depending on the complexity of the fix, sources may be required
  
Note we only maintain Dortania guides, so please do not open issues for other guides.

**Comment by PMheart** [comment]
Hello! Please post on forums for support.
