### ISSUE TITLE
Cannot disable touchbar on real macbook pro

### ISSUE THREAD

**Issue by sdanfa** [dortania/bugtracker#198]
Hello,
I want to disable the touchbar completely on my mbp 2015 and I'm getting a critical update is required error when trying to boot osx with opencore.

Image of the error: https://i.ytimg.com/vi/lYah-npwqcA/maxresdefault.jpg

Please provide a way to disable the touchbar completely to solve this issue.

Thanks.

**Comment by PMheart** [comment]
Hello! Please use forums for support.
