### ISSUE TITLE
CFG lock guide - mentions deprecated VerifyMsrE2.efi which no longer exists?

### ISSUE THREAD

**Issue by WWWFWWW** [dortania/bugtracker#202]
GUIDE: Checking if your firmware supports CFG Lock unlocking
https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock

ISSUE: Text with links not working, mentioned efi tool deprecated and no longer exists!

_Checking via VerifyMsrE2
To start, download VerifyMsrE2 (opens new window) and add this tool inside EFI/OC/Tools and config.plist(this can be done with ProperTree's snapshot function(ie. Cmd+R)). Next, boot OpenCore and select the VerifyMsrE2.efi entry. This should provide you one of the following:_

DL links to https://github.com/acidanthera/OpenCorePkg/releases, any late releases no longer include VerifyMsrE2.efi. The tool seem to have been deprecated. Update the guide with new instructions?

**Comment by jeremy0519** [comment]
It's now called `ControlMsrE2.efi` .It's easier to use since it supports argument `unlock` (or `interactive`) and no other tools are needed.

**Comment by PMheart** [comment]
Hello! This has already been fixed.
