### ISSUE TITLE
Provided Mac OS X 10.5.7 image does not letting me install

### ISSUE THREAD

**Issue by SkyrilHD** [dortania/bugtracker#205]
# Bug Description 
Hello, I do not know if it is the right place to ask but I tried doing a legacy Hackintosh and it is working quite well. But I wanted to try Mac OS X Leopard, so I downloaded the image from the guide found here: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install-dmg.html

With this image I got the furthest, as other Leopard images or my Install DVD stuck at `AppleIntelCPUPowerManagement: initialization complete`.

My EFI is not the prettiest as I uploaded it as is but it does boot from Snow Leopard up to Yosemite. As in the guide mentioned, 10.4 and 10.5 boot via i386, so I also set the Arch of FakeSMC to i386, too. Also the DSDT is from the trashOS repo by khronokernel which can be found here: https://github.com/khronokernel/trashOS. Even though the DSDT is meant for dc7900, it works with my dc7800 perfectly (I know I should not do that). But for some reason my HPET patch on e.g. Snow Leopard does not work, if I do not use the provided DSDT, but Mountain Lion and up are working perfectly. Using the ACPI patch for forcing HPET is a no-go as my Ethernet and Firewire card are not working.

# Specs
- HP Compaq dc7800
- Intel Core 2 Duo E6550
- 2 GB 667Mhz RAM
- 60GB HDD
- NVIDIA GeForce 9300GE
- BIOS version: v1.35 (latest)
- OpenCore version: 0.6.9

# Pictures and EFI
[EFI.zip](https://github.com/dortania/bugtracker/files/6460582/EFI.zip)
![IMG_20210511_175024](https://user-images.githubusercontent.com/28839925/117849975-24a32c00-b285-11eb-82a9-364e2f0f6990.jpg)
![IMG_20210511_175106](https://user-images.githubusercontent.com/28839925/117850016-308eee00-b285-11eb-8863-bdc2ac42436c.jpg)

**Comment by PMheart** [comment]
Hello! Please follow https://github.com/dortania/bugtracker/issues/205#issuecomment-907394427 instead.

**Comment by Florin9doi** [comment]
The guide is still wrong
