### ISSUE TITLE
Update some images - Low Priority

### ISSUE THREAD

**Issue by 1alessandro1** [dortania/bugtracker#206]
* Guide(s) in question: OpenCore Post-Install
* Link to page(s) with the issue https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#opencore-beauty-treatment
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
* Include possible fixes
`PlayChime` is not a boolean anymore, hence the image is incorrect

![image](https://user-images.githubusercontent.com/46293832/118643425-d4741e80-b7dc-11eb-9d3b-828ba54ac11d.png)

The `Resources/` folder includes `Audio/`, `Font/`, `Image/` , `Label/` and the image here is outdated too:

![image](https://user-images.githubusercontent.com/46293832/118643603-10a77f00-b7dd-11eb-8435-d90e8cfe27c5.png)

**Comment by dhinakg** [comment]
Closed in favor of #215
