### ISSUE TITLE
[XPS 15 9500] Power consumtion 20w+ on idle

### ISSUE THREAD

**Issue by GabeThatGuy** [dortania/bugtracker#208]
Hey folks, thanks for reading this
So here's my issue. When booted into macOS, everything works perfectly. Except the battery life. 
According to intel power gadget, the package power is 5w, which is completely fine for my CPU.  However, according to iStat menus, the total power draw from the battery is 20w, which makes sense since im getting 3-4 hours of run time on an 80wH battery. So what I'm trying to solve is what the heck is causing the power draw. Before installing OpenCore, battery was just fine on windows (12-14 hours run time on idle). Now, I use OpenCore to boot macOS and windows, so battery life is the same in macOS and windows. 

As I was writing this, github decided to be an asshole and not let me upload my EFI so here's a google drive link:
[https://drive.google.com/file/d/1RVrGPgFJk2eCLpZ2chkN8nMc2ZTp6zKu/view?usp=sharing](https://drive.google.com/file/d/1RVrGPgFJk2eCLpZ2chkN8nMc2ZTp6zKu/view?usp=sharing)

**Comment by PMheart** [comment]
Hello! Please use forums for support.
