### ISSUE TITLE
Q&A with icon/images in your repo when translating

### ISSUE THREAD

**Issue by Cokaps** [dortania/bugtracker#210]
Hi there. I'm translating your guide into Vietnamese and I have 2 questions:

* Can I keep all your icons/images the same?
* Can I change them into another as well? (Some need to be changed, but others don't)

My repo is here: https://github.com/viOpenCore/OpenCore-Install-Guide

**Comment by dhinakg** [comment]
Hi there, thanks for putting in the effort to translate it!

> Can I keep all your icons/images the same?

If by images you're referring to screenshots, sure. Not sure what you're referring to by icons though.

> Can I change them into another as well? (Some need to be changed, but others don't)

If the screenshots are outdated/need to be translated, sure - if they are outdated, however, we would appreciate if you upstreamed the changes too.

**Comment by Cokaps** [comment]
I mean those icons in public (for example dortania-logo-clear.png, could I change them into my own icon)

**Comment by khronokernel** [comment]
Dortania icons are for usage within our organization. Users see the icon and know who created the content. With 3rd party projects, we don't feel comfortable having our logos endorse projects we have little control over.

Feel free to use other images such as screenshots but we ask not to use dortania's icons
