### ISSUE TITLE
Kernel Panic due to voodooinput enabled in both voodooi2c and voodoops2controller

### ISSUE THREAD

**Issue by xenonstride** [dortania/bugtracker#211]
* Guide(s) in question : OpenCore Install Guide
* Link to page(s) with the issue : All Laptop Config.plist sections
* Clearly explain the issue(s) with the page(s) : When snapshot is used with propertree, voodooinput.kext plugin from both voodooi2c and voodoops2controller are added and enabled. Due to which a kernel panic occurs with the following messsage : refusing new kext me.kishorprins.Voodooinput, v1.1.3: already have prelinked v1.1.1
* Include possible fixes : Add a note to disable either one of them to fix the problem

**Comment by dhinakg** [comment]
Already present in https://github.com/dortania/OpenCore-Install-Guide/blob/master/config.plist/README.md and https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md
