### ISSUE TITLE
Warning regarding USBInjectAll kext and XhciPortLimit patch for MacOS 11.3+

### ISSUE THREAD

**Issue by xenonstride** [dortania/bugtracker#212]
The guide says to enable XhciPortLimit patch and use USBInjectAll kext both of which are broken on 11.3+
So maybe a warning for people installing 11.3+ and suggesting to use USBToolBox by DhinakG (https://www.reddit.com/r/hackintosh/comments/n2udl3/usbtoolbox%E1%B5%87%E1%B5%89%E1%B5%97%E1%B5%83_making_usb_mapping_simpler/)

**Comment by dhinakg** [comment]
Fixed in master
