### ISSUE TITLE
[Feature request] Add support for resumable downloads when downloading macOS

### ISSUE THREAD

**Issue by 1alessandro1** [dortania/bugtracker#220]
* **Guide(s) in question**: OpenCore Install Guide
* **Link to page(s) with the issue**: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os
* **Clearly explain the issue(s)**: users who download the default macadmin scripts to download macOS installer may fail and restart the whole thing if their connection drops
* **Include possible fixes**: With @dreamwhite I thought if it would be interesting to add support for `aria2c`. [The script](https://github.com/utopia-team/macadmin-scripts) works perfectly and it was tested by me and others multiple times, since it just has to download files and resume them if interrupted with `Ctrl+C`, by mistake or for faulty connection. I'm opening the issue to know if you might be interested to add the option to use a fork of the original script, maybe as an additional way to download the installer for those with unstable connections or who use their mobile carriers to download macOS.

**Comment by PMheart** [comment]
Hello! `aria2c` will work, while I do not think that we are supposed to teach users that here.

**Comment by 1alessandro1** [comment]
Hi, I thought `aria2c` could provide a more resilient solution, so it could've been best to at least include the option to have it if not replace the stock script which uses `curl` and is not able to resume anything in case of a connection drop or if servers become unreachable
