### ISSUE TITLE
Problem with keyboard selection, when OpenCore’s picker is used in GUI mode

### ISSUE THREAD

**Issue by Pbryanw** [dortania/bugtracker#225]
I use a Fnatic Ministreak keyboard on my PC. I’ve enabled the GUI for OpenCore’s picker by setting PickerMode to external in config.plist, and adding OpenCanopy.efi to EFI/OC/Drivers.

My issue is that when I use the arrow keys on the picker screen to select a drive, one press of the right or left key causes the selection box to get stuck in a loop. Video below:
https://1drv.ms/v/s!ArFVkgMSc1NUnP5_cT4_ePxq5_IBzw?e=jSXoUJ

This issue disappears when I disconnect my Fnatic keyboard, and instead use my wireless Logitech K360 Keyboard to control OpenCore’s picker. It can also be mitigated by enabling the Fnatic Keyboard’s BIOS mode which, I believe, disables N-Key Rollover. Their support doc says this “limits the number of keys that can be pressed at one time”. More information here: 
https://help.fnatic.com/support/solutions/articles/77000304065-how-do-i-enter-the-bios-uefi-mode-

I believe this problem only started with the last two or three versions of OpenCore. I'm currently using OC 0.7.1. Any help appreciated.

**Comment by dhinakg** [comment]
This repo is for dortania issues, not acidanthera ones. Please go to https://github.com/acidanthera/bugtracker
