### ISSUE TITLE
AGPM Error Boost Issue

### ISSUE THREAD

**Issue by ghost** [dortania/bugtracker#228]
I'm using OpenCore 0.7.2 on i5 10400 and RX580 as dGPU and UHD630 as headless iGPU. I realize that when im using SSDT-PLUG.aml (SSDTTime) x86PlatformPlugin is enable. However, i just check boot log appear something called 

"[AGPM][ERROR][BOOST       ][setBoost                ] 0 fGPUIdleIntervalMS = 0, ControlID = 17"

![Screenshot 2021-08-19 at 3 50 58 PM](https://user-images.githubusercontent.com/86180725/130029631-fdaf307e-1904-42cd-933c-3835d58e276e.png)

The problem solve if I removing SSDT-PLUG.aml but x86PlatformPlugin not enable. 
Is there any recommendation to me or any guide to fix this issue? I already follow the guide step by step and check if i am doing wrong. Is it related to Plugin type 1?

**Comment by PMheart** [comment]
Closing as the users have deleted their accounts.
