### ISSUE TITLE
OpenCore USB doesn't boot

### ISSUE THREAD

**Issue by Orlando17544** [dortania/bugtracker#229]
My computer doesn't recognize the OpenCore USB, the EFI structure of the usb is fine, secure boot is disabled from bios and my usb is formatted as vfat. My motherboard is asus prime b360m-a and my processor is intel core i3-9100f.

Thanks.

**Comment by TheHackGuy** [comment]
vfat? it should be formatted with fat32

**Comment by metacollin** [comment]
vfat _is_ fat32.  It is just a driver that uses hidden additional directories to deal with longer file names, but anything reported as 'vfat' for the filesystem is really just fat32.  

@Orlando17544 is CSM disabled as well?

**Comment by kernel-dev** [comment]
> vfat _is_ fat32. It is just a driver that uses hidden additional directories to deal with longer file names, but anything reported as 'vfat' for the filesystem is really just fat32.
> 
> @Orlando17544 is CSM disabled as well?

I'm fairly certain that you cannot use VFAT if something requires FAT32, as FAT32 is an extension of VFAT, not the other way around. So, no, anything reported as `VFAT` is _not_ FAT32.

You can use FAT32 for something that requires VFAT, but not the other way around.
