### ISSUE TITLE
Incorrect driver name in OC 0.7.3 Sample.plist and SampleCustom.plist

### ISSUE THREAD

**Issue by dhocker** [dortania/bugtracker#236]
In 0.7.3, the layout of the Drivers section was changed. In both the Sample.plist and CustomSample.plist files, the first driver in the Drivers section is listed as HfsPlus.efi. This should be OpenHfsPlus.efi. If you copy this section verbatim to your config.plist, OC will stop with a critical error saying "HfxPlus.efi at 0 cannot be found".

		<key>Drivers</key>
		<array>
			<dict>
				<key>Path</key>
				<string>HfsPlus.efi</string>
				<key>Enabled</key>
				<true/>
				<key>Arguments</key>
				<string></string>
			</dict>

**Comment by ArchCryptonIO** [comment]
You were lucky by read all the documentation well. So you realize the issue.

If someone read well the [Dortania OpenCore](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#universal) documentation, i'm sure they will notice this mistake and use stable [HfsPlus.efi].

**Comment by dhinakg** [comment]
![](https://i.dhinakg.tk/msedge_2021-09-10_17-10-57.png)
