### ISSUE TITLE
bluetooth BCM4331 cannot be used in macOS 12 (Wifi is usable)

### ISSUE THREAD

**Issue by Cuacon2004** [dortania/bugtracker#237]
I can't use bluetooth BCM4331 in macOS 12 beta 6.
My BCM4331 card is both Wifi and bluetooth.
I already install these kexts:
+ BrcmBluetoothInjector.kext (ver 2.6.1)
+ BrcmFirmwareData.kext (ver 2.6.1)
+ BrcmPatchRAM3.kext (ver 2.6.1)
+ AirportBrcmFixup.kext( for Wifi) (ver 2.1.4)
In Windows and Linux I can using wifi and bluetooth normally but in macOS, only wifi is usable.
Please help me, I know this card only support Catalina and lower but I think it's can be patched. please help me at least at Big Sur.

**Comment by dreamwhite** [comment]
As per [acidanthera's bugtracker issue #1669](https://github.com/acidanthera/bugtracker/issues/1669) and [BrcmPatchRam PR #12](https://github.com/acidanthera/BrcmPatchRAM/pull/12), you should replace `BrcmBluetoothInjector` with `BluetoolFixup`.

**Comment by Cuacon2004** [comment]
> As per [acidanthera's bugtracker issue #1669](https://github.com/acidanthera/bugtracker/issues/1669) and [BrcmPatchRam PR #12](https://github.com/acidanthera/BrcmPatchRAM/pull/12), you should replace `BrcmBluetoothInjector` with `BluetoolFixup`.

so I need to remove BrcmBluetoothInjector then add BluetoolFixup ?
And are you using BCM4331 ?

**Comment by Cuacon2004** [comment]
I'm using MacBook Pro wifi card BCM94331CSAX same with BCM4331

**Comment by dreamwhite** [comment]
> so I need to remove BrcmBluetoothInjector then add BluetoolFixup ?

You can either choose between:

1. set `MaxKernel` to `20.99.99` (up to Big Sur) on `BrcmBluetoothInjector`, and set `MinKernel` to `21.0.0` (from Monterey and so on) on `BluetoolFixup`
2. Remove `BrcmBluetoothInjector` and use `BluetoolFixup`. No other kexts are required

> And are you using BCM4331 ?

I'm using a DW1830 which is `BCM943602BAED` (BCM4360 based) and BT works flawlessly on Monterey (even turning off and turning back on).

I'm not a wizard neither I know every PCI ID in the world, but I think you can give a shot at [this sheet](https://docs.google.com/spreadsheets/d/1CNrDxBsmCbCTL_y9ZB7m3q3jHw5X2N8YaYb7IonQ3MI) originally wrote by @1alessandro1 and lately revised by me.

Please note that despite the sheet talks about WiFi, the integrated Bluetooth chip works (with the BrcmPatchRAM kexts if needed).

**Comment by Cuacon2004** [comment]
> > so I need to remove BrcmBluetoothInjector then add BluetoolFixup ?
> 
> You can either choose between:
> 
> 1. set `MaxKernel` to `20.99.99` (up to Big Sur) on `BrcmBluetoothInjector`, and set `MinKernel` to `21.0.0` (from Monterey and so on) on `BluetoolFixup`
> 2. Remove `BrcmBluetoothInjector` and use `BluetoolFixup`. No other kexts are required
> 
> > And are you using BCM4331 ?
> 
> I'm using a DW1830 which is `BCM943602BAED` (BCM4360 based) and BT works flawlessly on Monterey (even turning off and turning back on).
> 
> I'm not a wizard neither I know every PCI ID in the world, but I think you can give a shot at [this sheet](https://docs.google.com/spreadsheets/d/1CNrDxBsmCbCTL_y9ZB7m3q3jHw5X2N8YaYb7IonQ3MI) originally wrote by @1alessandro1 and lately revised by me.
> 
> Please note that despite the sheet talks about WiFi, the integrated Bluetooth chip works (with the BrcmPatchRAM kexts if needed).

I'm using monterey now so can use option 2. It's easier to config. I think so ?

**Comment by dhinakg** [comment]
Betas are unstable and the Bluetooth stack is currently very broken
