### ISSUE TITLE
Typo in ACPI > IMEI Section for IvyBridge

### ISSUE THREAD

**Issue by 5T33Z0** [dortania/bugtracker#241]
Article: https://dortania.github.io/Getting-Started-With-ACPI/Universal/imei.html#what-this-ssdt-does

Text: 

 **-  The same applies when mixing Sandy Bridge motherboards with 7 series motherboards"**

I think it should say "The same applies when mixing Sandy Bridge **CPUs** with 7 series motherboards" instead.

**Comment by PMheart** [comment]
Thanks! Fixed.
