### ISSUE TITLE
Cannot boot Mac OS12 beta3 or higher on B550 motherboard

### ISSUE THREAD

**Issue by wuwuwu223** [dortania/bugtracker#242]
All worked fine below this version,I think the CPUR.aml has something wrong.
![2EBEB04A-E6DD-40CB-BB5F-1904A572849E](https://user-images.githubusercontent.com/81224214/137083542-9bee77e9-b8fa-4bd7-b159-0e6b235dc830.jpeg)

**Comment by wuwuwu223** [comment]
> I don't get the point of opening this issue when clearly you're using:
> 
> * Clover
> * SSDT-RTC0 without correcting the paths
> 
> while Dortania's bugtracker requirements clearly say that only OpenCore and Lilu configuration are supported.
> 
> ![image](https://user-images.githubusercontent.com/17933708/137105110-ede51846-2d36-4706-b758-1526a0d6fad4.png)
> 
> SSDT-CPUR has nothing to matter in your case as you can see below :/
> 
> ![image](https://user-images.githubusercontent.com/17933708/137104929-6dd78dfc-6c94-4bd5-8b18-cbede6104f4d.png)
> 
> P.S. is there any specific reason you're using FakeSMC rather than VirtualSMC?

I'm using open core 0.7.4 ,use fakesmc kext it show clover,I'll retry to get true error log again later.When I use VirtualSMC Lilu show found dead device gfx0

**Comment by TheHackGuy** [comment]
Restrictevents has now the ability to fix these issues. Please read the release notes if latest restrictevents

**Comment by PMheart** [comment]
Hello! Please post on forums for support.
