### ISSUE TITLE
AMD Navi 21 clarifications

### ISSUE THREAD

**Issue by vit9696** [dortania/bugtracker#247]
Guide: https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html
 
We support RX 6900 XT (0x73AF) since WhateverGreen 1.5.2: https://github.com/acidanthera/bugtracker/issues/1618#issuecomment-950285641. It is enough to install new WEG and inject the `device-id` on macOS 11.x.

macOS 12 apparently [added support](https://forums.macrumors.com/threads/amd-polaris-vega-navi-gpu-macos-support.2083168/post-30464959) for 6900 XT (0x73AF), yet there are mixed reports whether it works or not without our patches. macOS 12.1 also supports RX 6600 XT (see [this link](https://developer.apple.com/documentation/macos-release-notes/macos-12_1-release-notes)), yet 6700 XT is still unsupported.

**Comment by dhinakg** [comment]
@1Revenger1

**Comment by 1Revenger1** [comment]
Added in https://github.com/dortania/GPU-Buyers-Guide/commit/9f22ff7a1fa7f8bc1f1f89af6aa1b1682e9b87de
