### ISSUE TITLE
Battery Not Charging

### ISSUE THREAD

**Issue by eslamo** [dortania/bugtracker#248]
Hi..

I spent a lot of time trying to figure a solution for my problem.

The problem is battery NOT CHARGING

Details:
- After Disassemble battery and Remove CMOS battery to hard clear CMOS and for first boot battery works great and charge and works fine.
- After battery reach more than 89% and do a restart I get Battery not charging.
- If I disconnect both batteries from laptop to reset CMOS it works again until restart.
- do reset default from bios menu not working** I must disconnect the batteries from motherboard
- do nvram reset not working**

After some diagnostics The battery is 5150mAH and what is in System Information is 4064mAH

Also I tried to boot windows and status stick to not charging and HP Support Utility shows Battery as Unknown.

But after disconnect batteries as i mentioned above HP tools shows that battery is normal and charging

Can anyone help me to find a solution for this problem that is very annoying and I really can't figure how to deal with it
![140029506-c74424b6-9d8c-4aca-b15b-c30d9e4c14d9](https://user-images.githubusercontent.com/2030376/140291930-790a3e25-877e-4f6a-b980-95fde4fe9ac0.png)
![140029485-6fc8be02-71e6-45ae-ae7f-379bcf5535e8](https://user-images.githubusercontent.com/2030376/140291940-a273e1a2-fe93-4645-9fa1-e1ca421b352f.jpg)

[IORegExplorerDump.zip](https://github.com/dortania/bugtracker/files/7473797/IORegExplorerDump.zip)
[DSDT.aml.zip](https://github.com/dortania/bugtracker/files/7473799/DSDT.aml.zip)
[EFI.zip](https://github.com/dortania/bugtracker/files/7473800/EFI.zip)
.

**Comment by 1Revenger1** [comment]
Sounds like a firmware bug of some sort, or something that needs to be done in ACPI maybe?
Not something that is an issue with the guides I think, first time I've seen this.
