### ISSUE TITLE
Update Boot chime guide for OpenCore 0.7.8

### ISSUE THREAD

**Issue by matteodev8** [dortania/bugtracker#258]
* **Guide(s) in question**: OpenCore Beauty Treatment/Setting up boot chime
* **Link to page(s) with the issue**: https://github.com/dortania/OpenCore-Post-Install/blob/master/cosmetic/gui.md#setting-up-boot-chime-with-audiodxe
* **Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)**: I tried to set up the boot chime but in the newest OC (0.7.8) some things are missing under UEFI -> Audio.
* **Include possible fixes**: 
  Update this part of the guide to be compatible with OpenCore 0.7.8

**Comment by perez987** [comment]
[Setting Boot Chime guide updated to OC 0.7.8 #115](https://github.com/dortania/OpenCore-Post-Install/pull/115)
