### ISSUE TITLE
https://dortania.github.io/docs/latest/Configuration.html

### ISSUE THREAD

**Issue by kokowski** [dortania/bugtracker#259]
I always used this link (https://dortania.github.io/docs/latest/Configuration.html) to look into actual configuration guide (same as the Configuration.pdf in OC), but now it's not available anymore.

**Comment by kokowski** [comment]
Thank you very much for the useful information.

**Comment by dhinakg** [comment]
Builder broke, investigating

**Comment by kokowski** [comment]
Thanks for fixing this.
