### ISSUE TITLE
Thinking about a "Style Guide"

### ISSUE THREAD

**Issue by richb-hanover** [dortania/bugtracker#26]
Newcomers to Hackintosh face significant hurdles in understanding the documentation, in addition to the ordinary technical problems they encounter. I want to get the documentation to be clear without "spoon feeding" anyone. 

As we work through revisions to the Laptop and Desktop guides, it seems it would help to come up with standard ways to write about OpenCore, the bits and pieces of software that are required, and the steps of the process. For example:

1. We should choose a canonical name for big concepts, then use them everywhere. I was confused by the usage of some of the following terms:
- Recovery/online installer, 
- Full/offline installer, 
- OpenCore bootloader
- USB drive (sometimes the guide uses "installer" - how is that distinguished from the macOS "installer"?)
- Target computer (the one being Hackintoshed)
- "OpenCore Laptop Guide" instead of "Vanilla Laptop Guide", and as a sister document to the "OpenCore Desktop Guide"

2. What tone are these Guides aiming at? Formal? Informal? For example, the following from the Installation page seemed a bit too informal: '... it should finally plop you at the "Setup your Mac screen"...'

3. Should Hackintosh always be capitalized? Is "to Hackintosh" a verb? (I'm OK with it.) 

4. I would like to propose the use of the term "newcomer" to Hackintosh, and use that name for the reader where it's warranted. This person isn't necessarily a "noob" (who may or may not have any computer skills, and definitely isn't our audience) but might be someone with decades of computer experience who is simply new to the Hackintosh project.

5. Replace occurrences of, "You will want to do X..." with "Do X..." Most of the time, readers look to the guide to tell them what to do, not to exercise judgement about topics that they don't completely understand. So if it's a mandatory step, remove "you will want to X") and just say "X". If there's a choice to be made ("you may want..."), the text should include enough information to make an informed decision.

6. Similarly, seek out places that say "... make sure that..." and state it in a declarative sentence. For example change, "Make sure the laptop is connected to the charger..." to the simpler, "Connect the laptop to the charger..."

We don't have to decide these right now, or implement them immediately. 

I'm about to send a PR that contains a bunch of fixes to these usages, as well as edits to some of the overview documents. Review that PR, and see how the wording feels...

**Comment by dreamwhite** [comment]
@richb-hanover is there any news about this PR? ^^

**Comment by richb-hanover** [comment]
The PR was shut down pretty hard (see https://github.com/dortania/OpenCore-Install-Guide/pull/147#issuecomment-683175654) so doesn't seem that the team agrees with these thoughts.

I was able to get my Hackintosh going mostly with the help of OSX Latitude...
