### ISSUE TITLE
F*cking Usb ports won't work

### ISSUE THREAD

**Issue by gastercraft-minecraft** [dortania/bugtracker#266]
Hi,
i'm doing an hackintosh with the last version of OC.
The config is ready, i have SSDT EC USBX in my config and my ACPI folder, 
but when i turn my "mac" on, my mouse power off.
I tried to disable XhciPortLimi and ReleaseUsbOwnership, nothing.
Can you help me ?
My logs : i don't have any 
My config : https://www.mediafire.com/file/6l3htjb72pbk9dy/config.plist/file
I'm on the last catalina version with basesystem.dmg and basesystem.chunklist
i have usb inject all, the correct path in my config.plist, a 100% compatible material.
Thanks :')

**Comment by gastercraft-minecraft** [comment]
CPU: Intel Core i3 10105 Comet Lake
GPU: Integrated GPU : UDH Graphics 630
SSD (every single SSD, even the ones you won't use on macOS) : i havn't installed macos because of my usb port, but i have a Western Digital Disque SSD SATA WD Blue™ M.2 2280, who works on a real macbook pro 2015
Motherboard: Asus Prime h510m-e
BIOS Version: 1017 (7 december 2021)

UPDATE : I mapped my ports, deleted SSDT rhub and EC-USBX, but the ports still not working, i've turn on the ReleaseUsbOwnership, NOTHING.
Thx ;)

**Comment by gastercraft-minecraft** [comment]
my os start, just my usb port not working, but catalina loads perfectly
it's just my ports who doesn't work

**Comment by gastercraft-minecraft** [comment]
i think i will try clover :/

**Comment by dreamwhite** [comment]
> QE/CI? Idk what it is, but my MotherBoard is supported by opencore.. so it's strange that my usb ports orks like that (and i updated my last responce with screens and text, go ckeck pls) thx

Graphics acceleration



> my os start, just my usb port not working, but catalina loads perfectly

Maybe it loads """perfectly""" but without a proper EFI folder you can't call it a perfect one.



> i think i will try clover :/

Without a proper documentation? Feel free to having headache on the desk haha
