### ISSUE TITLE
Guide Clarifications/Troubleshooting for SATA Drives

### ISSUE THREAD

**Issue by jermafenser** [dortania/bugtracker#27]
In short, my laptop (HP Pavilion 15-dk0030nr) would not initially detect the SATA drive.  A lot of googling suggested a handful of things:

- Setting SATA to AHCI in the BIOS
  - However, my BIOS is pretty locked down and doesn't any options for SATA configuration
  - It seems like this is mainly intended for IDE vs AHCI in older devices?
  - Intel Rapid Storage Technology seems to expose itself as a RAID controller (but apparently also exposes AHCI)
 - A lot of (mostly) unhelpful information regarding clover configurations
   - SAT0 -> SATA (which the OpenCore clover conversion guide indicates is cosmetic)
   - AHCIPortInjector.kext (seems to be related to third-party controllers)
 - SATA-unsupported.kext 
   - https://github.com/RehabMan/hack-tools/tree/master/kexts/SATA-unsupported.kext
   - This has fixed my issue (my controller is 'pci8086,282a'), but it is the correct thing to do in general?
   - Perhaps spoofing the device id in the config.plist would be a better approach?  But which device id should it be spoofed to?

As a result, I think it would be helpful for other users if the guides included some clarifications/troubleshooting for SATA drives.  This seems to be a gap in the documents and would hopefully save others some time.

**Comment by khronokernel** [comment]
Sorry this took so long to get back to, makes sense to add info on it. Added in this PR: https://github.com/dortania/OpenCore-Desktop-Guide/pull/89

> Intel Rapid Storage Technology seems to expose itself as a RAID controller (but apparently also exposes AHCI)

If the drive has already been setup with RST in Windows/Linux, macOS won't be able to access the drive

> It seems like this is mainly intended for IDE vs AHCI in older devices?

Some BIOS allow you to set your SATA controller into RAID mode as well, but ATA/IDE and RAID are the 2 modes that cause issues.

> This has fixed my issue (my controller is 'pci8086,282a'), but it is the correct thing to do in general?
Perhaps spoofing the device id in the config.plist would be a better approach? But which device id should it be spoofed to?

Honestly the SATA-unsupported.kext route is more than adequate. Ideally spoofing the device-id would avoid 1 less kext but SATA-unsupported is already cordless making it quite difficult to break
