### ISSUE TITLE
iGPU Connectors patch not working

### ISSUE THREAD

**Issue by MaydayAlaska** [dortania/bugtracker#270]
Files [HERE](https://github.com/MaydayAlaska/Bugtracker-igpu-patching)

I'm trying to make audio over HDMI working on this configuration:

i7 10700
z490i Aorus Ultra

According to WEG's manual:
```
To enable digital audio it is necessary to set the hda-gfx properties and patches the connectors.
To enable audio in general and HDMI in particular use WEG along with [AppleALC.kext](https://github.com/acidanthera/AppleALC). AppleALC automatically injects missing hda-gfx properties.
On 10.10.5 and above, WEG automatically changes the connector-type of DP (00040000) to HDMI (00080000), only if not used Custom patching. Physical connection may be of any type (HDMI, DVI, DP), but for the digital audio connector-type must explicitly be HDMI.
```

So, I was trying to manually patch my HDMI connector (following [this guide](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#parsing-the-framebuffer)) as `00080000`, disabling every other connector by setting the BusID as `00`

What happens next is kinda weird:

- even though I disable every other connector, both my DP and HDMI work;
- somehow, `FakePCIID.kext` and `FakePCIID_Intel_HDMI_Audio.kext` do not get injected (yes, I have them enabled in `Kernel>Add`;
- if I connect both the connectors, 2 new audio outputs pop out with DP type. One of them carries audio to my DP connection and works, the other one doesn't work at all;
- IOREG shows my manual patch correctly.

**Comment by PMheart** [comment]
Hello! Please use forums for support. Or, if you believe that this is a bug of WhateverGreen, please file an issue at Acidanthera. Thanks!
