### ISSUE TITLE
Asus Vivobook x712JA Ice Lake [IGFB] [PANIC] [DISPLAY] issue

### ISSUE THREAD

**Issue by VickyGumiho** [dortania/bugtracker#273]
I really need help, i'm going crazy with this kernel panic, also i can't find anyone with similar issue
I tried all the ig-platform-id in Ice Lake section mentioned by WhateverGreen iGPU patching manual
tried all the device ID and also tried many different boot-args provided by Whatevergreen kext
However nothing changing, i can boot without graphic acceleration (-igfxvesa)

Asus Vivobook 17 x712JA
Processor: Intel Core i7 1065G7
Graphics: Intel Iris Plus G7
No dGPU
Bios setup according to the OpenCore guide, as well as config
Please. Help me

[Screen Shot 2022-05-29 at 1 41 43 PM](https://user-images.githubusercontent.com/105861795/170901386-cbf87201-3907-4108-a4c3-acd4a1d16668.png)
[opencore-2022-05-29-203823.txt](https://github.com/dortania/bugtracker/files/8794770/opencore-2022-05-29-203823.txt)

**Comment by PMheart** [comment]
Hello! Please use forums for support.
