### ISSUE TITLE
NVRAM Maybe Broken?

### ISSUE THREAD

**Issue by MiloVeritas** [dortania/bugtracker#274]
Issues saving NVRAM Data on 0.8.1 and 0.8.2, 0.8.0 is fine, can't select boot drive on System Preferences, Data isn't being saved.

**Comment by dhinakg** [comment]
This is not related to the guides. Please troubleshoot on the forums and if determined that it's an OpenCore issue, open an issue at [acidanthera's bugtracker](https://github.com/acidanthera/bugtracker).
