### ISSUE TITLE
UEFI Secure Boot - OC: Driver HfsPlus.efi at 0 cannot be loaded - Invalid Parameter!

### ISSUE THREAD

**Issue by karlo922** [dortania/bugtracker#275]
Hi,

I have a working 0.8.1 DEBUG configuration. I then signed all .efi files (boot, oc, drivers) with my own private keys and included them into my UEFI (Lenovo T450S).
The boot with UEFI Secure Boot will stop before the boot-menu-picker with following error:
`OC: Driver HfsPlus.efi at 0 cannot be loaded - Invalid Parameter!`

I attached the log and the EFI folder (deleted all Kexts to get <25MB).

When I delete the HfsPlus driver in the config.plist, it will stop with the next given driver with the same error.
It will boot fine as soon as I disable "Secure Boot" in my UEFI. 

As OpenCore itself is loading, the signing and enrolling in my UEFI worked, else it would not get that far.

Something seems to be wrong with loading the signed drivers
[EFI.zip](https://github.com/dortania/bugtracker/files/8921951/EFI.zip)
[opencore-2022-06-16-190700.txt](https://github.com/dortania/bugtracker/files/8921952/opencore-2022-06-16-190700.txt)
.

**Comment by karlo922** [comment]
> Use HfsPlus.efi from https://github.com/acidanthera/OcBinaryData

I already use this file. And even if I delete the HfsPlus.efi in my config (as I currently do not need it) it will stop with the next driver like OpenRuntime.efi with the same fault.

**Comment by karlo922** [comment]
Is it possible to further debug whats happening here?

**Comment by karlo922** [comment]
What I now tested:
UEFI Secure Boot ENABLED:
1.
- BOOTx64.efi NOT signed -> stops direcly with UEFI Screen "ACCESS DENIED" -> as expected

2.
- BOOTx64.efi SIGNED
- OpenCore.efi, HfsPlus.efi, OpenRuntime.efi, OpenCanopy.efi NOT signed -> stops half a second later with UEFI Screen "ACCESS DENIED" -> as expected

3.
- BOOTx64.efi SIGNED
- OpenCore.efi SIGNED
- HfsPlus.efi, OpenRuntime.efi, OpenCanopy.efi NOT signed -> exaclty same error as when they are signed `OC: Driver HfsPlus.efi at 0 cannot be loaded - Invalid Parameter!`

So it seems that as soon the UEFI Secure Boot is enabled, the loading of the drivers fails. Independent if they are signed or not.

**Comment by karlo922** [comment]
I now tried to debug further and made all variables from OpenCoreUefi.c visible which were loaded:

`ImageHandle = NULL;
    Status      = gBS->LoadImage (
                         FALSE,
                         gImageHandle,
                         NULL,
                         Driver,
                         DriverSize,
                         &ImageHandle
                         );`

But this still seems to be valid.

Output of non-signed drivers with SecureBoot Disabled:
`08:523 00:295 OC: Driver HfsPlus.efi with argument '', DriverSize: 37892 with ImageHandle: 3224682864 at 0 with gImageHandle 3306163864 and DriverHandle 3288682520 loaded - Success!`

Output of signed drivers with SecureBoot Enabled:
`09:023 00:299 OC: Driver HfsPlus.efi with argument '', DriverSize: 39488 with ImageHandle: 3224682864 at 0 with gImageHandle 3288707736 and DriverHandle 3288637464 cannot be loaded - Invalid Parameter!`

**Comment by PMheart** [comment]
Hello! Unfortunately I don’t think this is what Dortania could help with; please use forums for support.
