### ISSUE TITLE
AAPL,ig-platform-id for Coffee Lake (i7 8700K with Gigabyte b365m ds3h) should be 0x3E9B0007 instead of 0x07009B3E for Monterey

### ISSUE THREAD

**Issue by achal1012** [dortania/bugtracker#276]
* Guide(s) in question
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#deviceproperties 
* Link to page(s) with the issue
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#deviceproperties
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
I have been trying to make my config.plist with 0x07009B3E or 0x00009B3E as values and after unsuccessful attempts I also tried: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#mapping-the-video-ports this but at then end this value worked for me: 0x3E9B0007
<img width="915" alt="image" src="https://user-images.githubusercontent.com/4771917/174702162-640cd4d2-ec73-4a77-af1f-916d2b12980e.png"> from https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md 

Can you please either add this directive or maybe explain why this would have worked for me? 

Thank you for writing this amazing guide :)

**Comment by dhinakg** [comment]
Unless you were hexswapping the values we gave on the guide (which are already hexswapped), this doesn't make much sense. Closing as user error
