### ISSUE TITLE
Open Core BigSur installation problem C612 Asus Z10PA-U8

### ISSUE THREAD

**Issue by macosnexus** [dortania/bugtracker#278]
When installation comes to 13 minutes left. it restarts and i starting with installer partition on SATA Harddrive.
but in this case, installer always restarts and i could not get debug log about it.

I am sending more than one debug log from opencore.
only last 2 can be determined for my latest tries to install again.
i also tested with another GPU before last ones. GPU: ASUS AMD r7 240.
My Hardware is
GPU: nvidia GT 710 2 GB asus
CPU : e5-2620 v3
Mainboard : Asus Z10PA-U8
Ram : 8 GB DDR4 ECC
[Bigsur_Bug_Report_20220704172454.zip](https://github.com/dortania/bugtracker/files/9041263/Bigsur_Bug_Report_20220704172454.zip)

i also have similar problem about high sierra.
if you can find the problem, i will be happy.

**Comment by dhinakg** [comment]
This is not related to the guides. Please troubleshoot on the forums.
