### ISSUE TITLE
Replace VoodooTSCSync Kext into CpuTscSync Kext

### ISSUE THREAD

**Issue by KhoraLee** [dortania/bugtracker#28]
Replace VoodooTSCSync into CpuTscSync on Gathering Files and General Troubleshooting

RehabMan's VoodooTSCSync is no longer updated and there's replacement kext called CpuTscSync

https://github.com/lvs1974/CpuTscSync

I think CpuTscSync would be better

**Comment by khronokernel** [comment]
See little sense to too, changed them here: https://github.com/dortania/OpenCore-Desktop-Guide/pull/86
