### ISSUE TITLE
Hey i have problem with my wifi

### ISSUE THREAD

**Issue by MohamedSaberM** [dortania/bugtracker#287]
hello I have problem with my wifi card : ( qualcomm atheros qca9377 802.11ac wireless network adapter)
can you help me please?
iOS is Ventura 13 Beta 7

**Comment by dreamwhite** [comment]
Unsupported card. Change it for a compatible one like the Fenvi BCM94360NG

**Comment by MohamedSaberM** [comment]
We don't have solutions ? Any thing except change because i have laptop 😢. 
And my touchpad not working how i can solve this problem ??

**Comment by MohamedSaberM** [comment]
Y

**Comment by dhinakg** [comment]
Not supported, go to the wireless buyers guide for supported cards. This is not a support forum
