### ISSUE TITLE
Setting Boot Chime guide updated to OC 0.7.8

### ISSUE THREAD

**Issue by perez987** [dortania/bugtracker#288]
In OpenCore 0.7.8 there were major changes in UEFI -> Audio.
This issue attempts to update the Setting Boot Chime guide to accommodate OpenCore 0.7.8 and later.
Changes made:

- audio file is now MP3 instead of WAV
- UEFI -> Audio has changes in several keys
- audio-config.png image has also been updated.

Thanks for your great work.

====================================

## Setting up Boot-chime with AudioDxe

So to start, we'll need a couple of things:

* Onboard audio output
  * USB DACs will not work
  * GPU audio out is a hit or miss
* [AudioDxe](https://github.com/acidanthera/OpenCorePkg/releases) in both EFI/OC/Drivers and UEFI -> Drivers
* [Binary Resources](https://github.com/acidanthera/OcBinaryData)
  * Add the Resources folder to EFI/OC, just like we did with the OpenCore GUI section
  * For those running out of space, `OCEFIAudio_VoiceOver_Boot.mp3` is all that's required for the Boot-Chime
* Debug version of OpenCore with logging enabled
  * See [OpenCore Debugging](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html) for more info
  * Note: after you're done setting up, you can revert to the RELEASE builds

**Settings up NVRAM**:

* NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82:
  * `SystemAudioVolume | Data | 0x46`
    * This is the boot-chime and screen reader volume, note it's in hexadecimal so would become `70` in decimal; `0x80` means muted

Optional
* NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82:
  * `StartupMute | Data | 0x00`
    * Mute startup chime sound in firmware audio support; 00 is unmuted, missing variable or any other value means muted

**Setting up UEFI -> Audio:**

* **AudioCodec:** (Number)
  * Codec address of Audio controller. This typically contains the first audio codec address on the builtin analog audio controller (HDEF). Failsafe value is 0.
  * To find yours:
    * Check [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip) -> HDEF -> AppleHDAController -> IOHDACodecDevice and see the `IOHDACodecAddress` property (ex: `0x0`)
    * Can also check via terminal (Note if multiple show up, use the vendor ID to find the right device):

      `sh ioreg -rxn IOHDACodecDevice | grep VendorID   // List all possible devices`
 
      `sh ioreg -rxn IOHDACodecDevice | grep IOHDACodecAddress // Grab the codec address`
 
* **Audio Device:** (String)
  * Device path (PciRoot) of audio controller
  * Run [gfxutil](https://github.com/acidanthera/gfxutil/releases) to find the path:
    * `/path/to/gfxutil -f HDEF`
    * ex: `PciRoot(0x0)/Pci(0x1f,0x3)`

* **AudioOutMask:** (Number)
  * Play sound in UEFI to more than one channel (e.g. main speaker plus bass speaker). Failsafe value is `-1` (output to all).
  * Output channels are internally numbered as bit `0` (value `1`), bit `1` (value `2`) and so on. A value of `1` refers to the first audio output (not necessarily main speaker). A value of `-1` is used to play to all channels simultaneously.
  * When AudioSupport is enabled, AudioDevice must be either empty or a valid path and AudioOutMask must be non-zero
  * Easiest way to find the right one is to go through each one (from 0 to N - 1, where N is the number of outputs listed in your log); ex: 5 outputs would translate to 0-4 as possible values
  * You can find all the ones for your codec in the OpenCore debug logs:

    ```
    06:065 00:004 OCAU: Matching PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000)...
    06:070 00:005 OCAU: 1/2 PciRoot(0x0)/Pci(0x1F,0x3)/VenMsg(A9003FEB-D806-41DB-A491-5405FEEF46C3,00000000) (5 outputs) - Success
    ```
* **AudioSupport:** (Boolean)
  * Set this to `True`
  * Enabling this setting routes audio playback from builtin protocols to specified dedicated audio ports (AudioOutMask) of the specified codec (AudioCodec), located on the specified audio controller (AudioDevice)

* **DisconnectHDA:** (Boolean)
  * Set this to `False`

* **MaximumGain:** (Number)
  * Maximum gain to use for UEFI audio, specified in decibels (dB) with respect to amplifier reference level of 0 dB
  * Set this to `-15`

* **MinimumAssistGain:** (Number)
  * Minimum gain in decibels (dB) to use for picker audio assist. The screen reader will use this amplifier gain if the system amplifier gain read from the SystemAudioVolumeDB NVRAM variable is lower than this
  * Set this to `-30`

* **MinimumAudibleGain:** (Number)
  * Minimum gain in decibels (dB) at which to attempt to play any sound
  * Set this to `-55`

* **PlayChime:** (String)
  * Set this to `Enabled`
  * Supported values are:
    * Auto — Enables chime when StartupMute NVRAM variable is not present or set to 00
    * Enabled — Enables chime unconditionally
    * Disabled — Disables chime unconditionally

* **ResetTrafficClass:** (Boolean)
  * Set this to `False`

* **SetupDelay:** (Number)
  * By default, leave this at `0`
  * Some codecs many need extra time for setup, we recommend setting to `500` milliseconds (0.5 seconds) if you have issues

Once done, you should get something like this:

<img width="616" alt="audio-config" src="https://user-images.githubusercontent.com/50429399/192841715-aa9314cb-f0f3-4b33-86b0-7a09f1923822.png">

**Note about audio codec default sampling rate**

There are codecs like Realtek ALC295 (HP models and others) whose default audio sampling rate is 48 kHz. In this case, even if 44.1 kHz is supported by the codec, audio chime fails and does not sound. The only way at the moment to fix this is to modify the `OCEFIAudio_VoiceOver_Boot.mp3` sample rate with an audio editor to raise it from 44.1 kHz to 48 kHz. This has to be done by the end user as OpenCore does not have an automated mechanism for it.

**Note for visually impaired**:

* OpenCore hasn't forgotten about you! With the AudioDxe setup, you can enable both picker audio and FileVault VoiceOver with these 2 settings:
  * `Misc -> Boot -> PickerAudioAssist -> True` to enable picker audio
  * `UEFI -> ProtocolOverrides -> AppleAudio -> True` to enable FileVault voice over
* See [Security and FileVault](../universal/security.md) on how to setup the rest for proper FileVault support.

**Comment by dreamwhite** [comment]
Please note that some codecs may require 48KHz sampling rate. Adding a side note would be helpful for users like me who had to convert the audio files

**Comment by perez987** [comment]
Thanks but, since this guide is only for UEFI sound (except ResetTrafficClass), where can we set the sample rate in UEFi >> Audio properties?
Or do you refer to codecs that require a specific sampling rate in the chime sound file (OCEFIAudio_VoiceOver_Boot.mp3) different to 44,1? Then, a side note about this?

**Comment by perez987** [comment]
@dreamwhite 
What audio codec do you have?

**Comment by dreamwhite** [comment]
> @dreamwhite What audio codec do you have?

Realtek ALC295 (ALC3254)

**Comment by perez987** [comment]
@dreamwhite 
Added note about audio codec sampling rate.

**Comment by perez987** [comment]
@dhinakg 

Good night. The `details Optional NVRAM entries` is shown as is, not as a spoiler or drop down text, do you see it also or is only me?

```
::: details Optional NVRAM entries

NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82:
StartupMute | Data | 0x00
Mute startup chime sound in firmware audio support; 00 is unmuted, missing variable or any other value means muted
:::
```

**Comment by perez987** [comment]
@dhinakg 
Good afternoon. There is something I can do to help you to finish this issue? Probably not but, if I can help, tell me.

**Comment by perez987** [comment]
If the PR is more comfortable to you, I can open it, of course. I guess you are busy, I'm sorry if it seems like I'm urging you, not at all, I really couldn't do it because I know the work you do for this community and for the many other things that each one of you will do outside of here.

**Comment by perez987** [comment]
@dhinakg 
Ok, PR opened.
[#](https://github.com/dortania/OpenCore-Post-Install/pull/117)
