### ISSUE TITLE
typo on PostInstall documentation

### ISSUE THREAD

**Issue by FRAMCHEZ** [dortania/bugtracker#289]
[#using-launcheroption](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html)
I am new to OC, starting with 0.8.5
OpenCore Post-install > Multiboot > Setting up LauncherOption > Prerequisites:

The line  "UEFI -> Quirks -> RequestBootVarRouting = True" think has a typo, using ProperTree-master the create config.plist, I got this option is here: PlatformInfo -> UEFI -> Quirks -> RequestBootVarRouting

thanks a lot for the hard work, regards

**Comment by perez987** [comment]
@FRAMCHEZ 
No, RequestBootVarRouting is within UEFI >> Quirks, PlatformInfo doesn't have an UEFI section.

**Comment by FRAMCHEZ** [comment]
Yep, sorry, I messed up my config.plist, for good, two days reading guide, still getting lingo, places, ... all
Sorry again, close this issue, please

**Comment by perez987** [comment]
@FRAMCHEZ
Close it yourself, the author of the issue can also to close it.
