### ISSUE TITLE
The install guide's URL misspelled

### ISSUE THREAD

**Issue by wangyanwen** [dortania/bugtracker#290]
Please stop and read this carefully. Otherwise your issue will be left **unanswered** and **closed**.

We require the following for guide issues:

* Guide(s) in question
* Link to page(s) with the issue
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
* Include possible fixes
  * Depending on the complexity of the fix, sources may be required
  
Note we only maintain Dortania guides, so please do not open issues for other guides.

hi,I'm a newbie,and studying your guide to install my hackintosh.
Thank you for your work.
In studying I found a URL misspelled:"https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html","winblows" perhaps misspelled.
Best regards.

**Comment by perez987** [comment]
@wangyanwen 
No, it's winblows, it must redirect to the `Making the installer in Windows` guide whose url is indeed https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html

**Comment by perez987** [comment]
Please close this issue, thanks.

**Comment by dreamwhite** [comment]
Winblows is the real name of Microsoft Windows. It blows up itself without no reason, hence I do not see any reason for this issue.

As @perez987 stated, close this issue using the button "Close issue"

**Comment by wangyanwen** [comment]
Oh,sorry.
I find the wiki:"Microshaft Winblows 98 is a 1998 interactive comedy video game for Windows and the Classic Mac OS. It parodies the then-upcoming Windows 98 operating system, as well as Microsoft co-founder Bill Gates. "
