### ISSUE TITLE
[OCLP] Why is SKL-as-KBL spoofing not being used?

### ISSUE THREAD

**Issue by OnesuchDev** [dortania/bugtracker#293]
I remember that SKL as KBL spoofing was discussed very early on in Ventura development and that it appeared to mostly work. 
Why isn't OCLP using it? Did it have issues that could not be resolved? 

I ask this because it would allow the MBP13,3 (see #292) and MB9,1 to run without root patching and get incremental OTAs.

**Comment by khronokernel** [comment]
1. Please don't use the bug tracker for OCLP. It's for the guide. Use discord
2. Spoofing will break DRM, and this was something we've found was quite important to most users back with Monterey and Ivy Bridge
