### ISSUE TITLE
Live Text and Copy Subject functions broken with MacBookPro9.2 (Ivy) and iMac17.1 (Skylake + R9 M390) on Ventura 13.1

### ISSUE THREAD

**Issue by bootlegseahorse** [dortania/bugtracker#299]
Sorry for posting this issue to the wrong place yesterday.

I just noticed another problem with Ventura 13.1 stable (22C65). The features "Live Text" and "Copy Subject" are both nonfunctional with unsupported models. I've tested with Photos, Quicklook, Preview and Safari, and it seems that all apps supporting those two features are now nonfunctional - you can't select any text or subject from photos and videos.

I tested with **MacBookPro9.2** _(i5-3210M **Ivy Bridge** iGPU)_ and **iMac17.1** _(i5-6500 **Skylake** iGPU + **Radeon R9 M390** dGPU)_, and both are broken. On the other hand, my HacBookPro14.1 _(i5-7200U **Kaby Lake** iGPU)_ is fully functional with those two features.

I can confirm that both models work perfectly fine with "Live Text" back on Monterey 12.6 or earlier (I used to heavily rely on this function from day to day). IIRC it used to be functional back in Ventura 13.0 and 13.0.1, but I'm not 100% sure about that. Also, I believe it's not associated with my personal data or iCloud or something, as the issue still exists on a fresh install with no personal data and no iCloud logged in.

I don't know if it's just me, or everyone is experiencing the same problem worldwide. My guess is that Apple added blacklists or whitelists for Live Text and Copy Subject functions in Ventura, but I can't guarantee that.

Any help is much appreciated. 

_OpenCore version: 0.8.7
OCLP version: 0.5.2
FeatureUnlock version: 1.1.1
Lilu version: 1.6.2_

Here are the Console.app logs when I tried to copy text and subject from the same picture in a Quicklook window. 

The first two pictures are from unsupported Macs (Radeon R9 M390 and Ivy Bridge), and the last picture is from a supported Hackintosh (Kaby Lake).

<img width="1569" alt="Radeon R9 M390" src="https://user-images.githubusercontent.com/97839352/208243303-1a2768cc-207a-44fe-9e6f-830cc8e003d1.png">
<img width="1393" alt="Ivy Bridge" src="https://user-images.githubusercontent.com/97839352/208243311-c5942c28-0227-44bd-bbd5-64d9beb2649f.png">
<img width="1812" alt="Kaby Lake" src="https://user-images.githubusercontent.com/97839352/208243306-729c1526-da34-412b-b5cb-3fdbbee818e8.png">

Thanks again to Acidanthera and Dortania for all the efforts to keep our computers running.

**Comment by bootlegseahorse** [comment]
Hi again! I just noticed that this issue has already been added to the [Legacy Metal Graphics Support and macOS Ventura](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/1008) page, as "Broken Live Text - Non-Functional - Intel Ivy, Haswell iGPUs and Nvidia Kepler GPUs (portions require Metal 2)". 

However I think that might not be the case, because my iMac17.1 _(Late 2015, i5-6500 Skylake iGPU + Radeon R9 M390 dGPU)_ is also have the "Broken Live Text and Copy Subject" issue. 

<img width="768" alt="Hackintool - iMac17.1" src="https://user-images.githubusercontent.com/97839352/208298718-604ca7bc-e678-4ab4-9671-24fc615585b4.png">

According to Hackintool, this Mac is only using the _R9 M390 dGPU_ for Metal support. The problem is, I believe this GPU naturally supports Metal 2. For instance, the Continuity Camera (which requires Metal 2) is working on it. The Full Screen Music.app Mini Player is also working fine. However - the Live Text and Copy Subject functions are still broken. I also remember that it used to be functional back in Ventura 13.0 and 13.0.1, but I'm not able to revert this iMac back to 13.0 at the time, so I can't confirm it. 

Below are the Console.app logs for Safari (functional Hackintosh and non-functional iMac).

<img width="1640" alt="Functional" src="https://user-images.githubusercontent.com/97839352/208298867-9c1a7e29-4720-41fb-84bb-f8c3c02420a5.png">
 
<img width="1569" alt="Non-functional" src="https://user-images.githubusercontent.com/97839352/208298855-73cda24c-e5e0-46ed-86b3-8727b50eac68.png">

Thanks again!

**Comment by khronokernel** [comment]
I'm impressed you completely ignored OCLP's own issues tab, and read what was pinned...
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/985

What was listed on OCLP's README:
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/README.md

Or what was listed on this repo's README:
* https://github.com/dortania/bugtracker/blob/master/README.md

----------

If you want Live Text resolved, fix it yourself. Apple's photo scan system, tied with mediaanalysisd, results in kernel panics on Metal 1 GPUs. OCLP is offered on an as-is basis, and maintained by a very small team of volunteers working with a closed source OS.

Use the community run discord if you want further support, as clearly listed on OCLP's README...
