### ISSUE TITLE
Video Playback issues MacPro6,1 Mac OS Ventura 13.1, OCP 0.5.3

### ISSUE THREAD

**Issue by paul072** [dortania/bugtracker#300]
[Configuration.pdf](https://github.com/dortania/bugtracker/files/10277850/Configuration.pdf)

On Mac Pro 2013 6,1
Problems playing purchased videos in TV.app - either cause hard freeze or playback window opens/closes quickly. Trying to play same purchased content via downloaded file in QuickTime Player shows crossed out 'play' button

Can't play Netflix via Safari Browser - playing any content forwards to the 'install silverlight' page - https://help.netflix.com/en/node/2090

I installed Ventura via OCP on MacBook Air 2014 6,2 - both purchased videos and Netflix work fine on this model. 
Thinking some kind of issue with graphics or HDCP?

**Comment by dhinakg** [comment]
**This is not a OCLP bugtracker.**
