### ISSUE TITLE
-x As A Boot Arg

### ISSUE THREAD

**Issue by STLVNUB** [dortania/bugtracker#304]
Possible bug 
booting with -x  results in no boot ever, the only way to fix it is with -v
Have filed a bug report to Apple as the bug MAY be their problem

**Comment by dreamwhite** [comment]
Just curious: is there any valid reason why you would boot with `-x` (aka safe mode)?

**Comment by perez987** [comment]
@STLVNUB 
I can boot with `-x` flag in config.plist, without `-v`. Reaching the desktop in safe mode. Z390 + i9-9900 + RX 6600 XT OC 0.8.9.

**Comment by dhinakg** [comment]
Please troubleshoot on the forums.
