### ISSUE TITLE
OPENCORE 6.1 HASWELL PATCH ON MACOS 13.3

### ISSUE THREAD

**Issue by wolffcatsky** [dortania/bugtracker#308]
Hello this is my first bug report so if I did it wrong please tell me.

I accidentally upgraded to macOS 13.3 beta.  System boots and asks for patches to be reinstalled.

I reinstall the patches but it will not boot freezes every time about half way.

I boot in safe node, remove patches, I can then boot normally but graphics are super slow.

I tried to downgrade but it won't let me.  I guess I can can erase and reinstall macOS or wait for next release and hope fixed?

**Comment by dhinakg** [comment]
This is not an OCLP bugtracker, please use OCLP forums for support.

**Comment by wolffcatsky** [comment]
Hello - I don’t need “support”, where is the appropriate place to reports OCLP bugs?On Feb 21, 2023, at 10:06 AM, Dhinak G ***@***.***> wrote:﻿
Closed #308 as not planned.

**Comment by dhinakg** [comment]
The OCLP bugtracker is closed until further notice as detailed in the pinned issue there. If you want to report an issue, you should go to the Discord, where you would find a message already posted regarding 13.3 beta 1.
