### ISSUE TITLE
Mbp11,4 can‘t recognize external display anymore ,after SMBIOS spoofing(mbp13,3)

### ISSUE THREAD

**Issue by l3rnao** [dortania/bugtracker#310]
Mac version:  MacBook Pro(Retina, 15-inch, Mid 2015)
OS version:  macOS Monterey 12.6.3
Opencore Legacy Patcher version:  0.6.1 GUI
Opencore Setrings: 
    SMBIOS Spoof Level:  Moderate
    SMBIOS Spoof Model:  MacBookPro13,3
- [x]    Allow Natvie Spoofs
- [x]     Allow native models
- [x]     Show Boot Picker

**Comment by dhinakg** [comment]
This is not an OCLP bugtracker, please use OCLP forums for support.
