### ISSUE TITLE
Black screen before language selection

### ISSUE THREAD

**Issue by anandjmp** [dortania/bugtracker#313]
When i installing ventura, after verbose and showing language selection, it is goes to black screen and no signal found in display. 

My pc config is coffee lake i7 8700k. and my current EFI is working fine in monterey

**Comment by perez987** [comment]
@anandjmp 
This is for support forms.
Do you have specific language or empty in prev-lang:kbd key?

**Comment by anandjmp** [comment]
No, I have not added this args

**Comment by perez987** [comment]
@anandjmp 
Try leaving it blank or with `656e3a323532` (en:252).

**Comment by perez987** [comment]
@anandjmp 
Please close the issue and go to support forums.
