### ISSUE TITLE
MacOS 13.3.1 (a) Security Response Update

### ISSUE THREAD

**Issue by wrwhite0132** [dortania/bugtracker#315]
After installation of this Security Update today (05/03/2023) my mac would get stuck half way thru the update on the Apple screen. This is how to fix this issue if you encounter it!
Turn off the Mac.
Press down the Left Shift button and hold until you have your login screen.
Login and load opencore patcher v0.6.4
RE-Run the POST INSTALL ROOT PATCH
Reboot.
Your system will boot up normal and you are back working again.
Just wanted to let everyone know how I recovered my mac before everyone thinks you have lost everything... This will fix the issue!

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/0.6.5

> Please note bug reports involving the following are not supported:
> * Bugs with OpenCore Legacy Patcher
>   * Bugtracker is meant for Dortania Hackintosh Guides
