### ISSUE TITLE
Autoclick OK button after upgrade to Ventura

### ISSUE THREAD

**Issue by marius3d** [dortania/bugtracker#318]
Hello, when you start macOS for the first time after a clean install or upgrade, OCLP starts automatically and asks you for OK to apply the patches. It would be very useful for the OK button to have a timer and be pressed automatically after 10 seconds, for example. Today I upgraded from Monterey to Ventura on a cMP and after the system booted I realized that I had no way to click OK in the OCLP window to apply (among other things) the patches for USB 1.1, it was a situation like the egg and the chicken.

**Comment by khronokernel** [comment]
Project needs elevated privileges immediately afterwards, so an auto countdown wouldn't do anything but instead display a password prompt afterwards.

And please, be respectful and read the repo's README before opening issues:
> Please note bug reports involving the following are not supported:
> * Bugs with OpenCore Legacy Patcher
>   * Bugtracker is meant for Dortania Hackintosh Guides
