### ISSUE TITLE
csr-active-config='E7030000'?

### ISSUE THREAD

**Issue by kommtzeitkonrad** [dortania/bugtracker#32]
What is the source for `csr-active-config=E7030000` that is mentioned in all examples at [OpenCore-Desktop-Guide/config.plist/](https://github.com/dortania/OpenCore-Desktop-Guide/tree/master/config.plist)? Calculating together all values from [darwin-xnu/bsd/sys/csr.h](https://opensource.apple.com/source/xnu/xnu-6153.81.5/bsd/sys/csr.h.auto.html) gives `csr-active-config=7FF00000`. See also [corpnewt's CsrDecode](https://github.com/corpnewt/CsrDecode):
![Bildschirmfoto 2020-06-27 um 10 32 36](https://user-images.githubusercontent.com/42938101/85918280-8a4f1b00-b861-11ea-8133-ca9bcb0632b7.png)

**Comment by khronokernel** [comment]
Well few things:
* 0x3E7 was High Sierra's SIP value, and with Mojave changed to 0x7FF as they added `CSR_ALLOW_EXECUTABLE_POLICY_OVERRIDE`
* `csr-active-config=7FF00000` is not correct, if properly hex swapped you'd receive `FF070000`
* macOS Big Sur now adds root auth to SIP so the final value now is 0x867 or `67080000` hex-swapped

I plan to update the guides with the last point sometime in the future but for now this is a low priority to fix, PR's are welcomed though

**Comment by kommtzeitkonrad** [comment]
> * 0x3E7 was High Sierra's SIP value […]

I've read this at a couple of sites, but it seems not to be true.
![Bildschirmfoto 2020-07-01 um 01 35 02](https://user-images.githubusercontent.com/42938101/86187029-1e0f3880-bb3b-11ea-9582-f4814a20ed0b.png)
All disabled [values known to 10.13 kernel](https://opensource.apple.com/source/xnu/xnu-4570.71.2/bsd/sys/csr.h.auto.html) sum up to `0x3ff`.
![Bildschirmfoto 2020-07-01 um 01 37 06](https://user-images.githubusercontent.com/42938101/86187143-67f81e80-bb3b-11ea-84e6-b23e1256fcd8.png)
> * `csr-active-config=7FF00000` is not correct, if properly hex swapped you'd receive `FF070000`

OF COURSE you are RIGHT! :-)

> * macOS Big Sur now adds root auth to SIP so the final value now is 0x867 or `67080000` hex-swapped

Next bit would be `0x800` and my calculator says this results in `0xfff`. :-)

> I plan to update the guides with the last point sometime in the future but for now this is a low priority to fix, PR's are welcomed though

I made some changes to that 'csr-active-config' part of the guide(s) that you can review here: https://github.com/kommtzeitkonrad/OpenCore-Desktop-Guide/commit/74e2b3ee5d6b2564e68f413bc8f755f701012f13

If we can agree to the values and the other additions I made, I'll make a PR.

**Comment by khronokernel** [comment]
Hmm the info looks good but another concern that popped up is overall encouragement of SIP disabling. Been trimming down the guides quite a bit of late and removing any unnecessary info, and SIP is one of them
There's no logical reason to mess with system files for 99% of use cases, maybe adding info to the troubleshooting section might be better. Plus SIP can be disabled via recovery like a real Mac as well.
Will likely pull info from that PR and put it into a page in troubleshooting.

**Comment by khronokernel** [comment]
Should be clarified now, thanks again for fixing these values!
https://github.com/dortania/OpenCore-Desktop-Guide/pull/86

**Comment by momomo** [comment]
Is this a reason? 

>> sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
Password:
/System/Library/LaunchDaemons/com.apple.metadata.mds.plist: Operation not permitted while System Integrity Protection is engaged
Unload failed: 150: Operation not permitted while System Integrity Protection is engaged

If you can not disable spotlight when you need to, I think it is valid to want to disable SIP. 

So the question is what is the correct value for disabling SIP for monterrey. 

FF0F0000 or E7030000 ... I've seen many variations, and recommendations.
