### ISSUE TITLE
Apple Drop Support for Broadcom Wifi in macOS 14

### ISSUE THREAD

**Issue by wqhqq1** [dortania/bugtracker#321]
So, would this patcher work for it in the future?
Or maybe just load the driver from Ventura?

**Comment by 1Revenger1** [comment]
You can not just load the driver from Ventura without downgrading other kexts.
This bug tracker is not for OCLP, and is for the hackintosh guides. You may be able to use OCLP to restore functionality in the future, but OCLP is aimed at legacy macs and does not officially support hackintoshes.
