### ISSUE TITLE
What is the correct value to disable SIP on Ventura?

### ISSUE THREAD

**Issue by michael1900** [dortania/bugtracker#323]
Installed Ventura with opencore on my old MacBook Pro model MacBookPro13,3;
 
with value 6F020000 **0x26f** i have: System Integrity Protection status: disabled BUT i no longer have brightness controls;
with value 870A0000 **0xA87**  i have: System integrity Protection status: unknown (Custom configuration) BUT still i have brightness controls;
with value FF0F0000 **0xFFF**  i have: System integrity Protection status: unknown (Custom configuration) BUT still i have brightness controls.

SIP is _disabled_ in all three cases because i can use TotalFinder.

<img width="572" alt="Screenshot 2023-06-07 alle 17 00 42" src="https://github.com/acidanthera/bugtracker/assets/1675875/071b2fda-0fe7-4fc7-b057-5a715bae205c">

So how to disable SIP _**correctly**_ without break brightness?

**Comment by michael1900** [comment]
> This is not a bug tracker for OpenCore Legacy Patcher, please use the appropriate channels:
> <img alt="Screenshot 2023-06-09 at 8 34 43 AM" width="649" src="https://user-images.githubusercontent.com/48863253/244723920-b5a37888-3a5a-41b2-9c4d-0fb695be65ef.png">

The bug tracker for OpenCore Legacy Patcher is closed. So where i can post it, please?

**Comment by khronokernel** [comment]
Look at what the repository says for support?
* https://github.com/dortania/OpenCore-Legacy-Patcher

You are using software on an AS-IS basis with zero support (reminder, this is free and entitled to no support), and we clearly mention a community Discord server in the README, in the Guide and in the app itself. 

-------

<img width="856" alt="Screenshot 2023-06-09 at 8 39 27 AM" src="https://github.com/dortania/bugtracker/assets/48863253/86780e74-89f4-43cd-a35b-1649a6f996f0">
