### ISSUE TITLE
Wifi in Sonoma

### ISSUE THREAD

**Issue by wqhqq1** [dortania/bugtracker#325]
I've tried the patch in the dev version of Sonoma.
Wifi worked but could not find any network.
Is there any thing not to be mentioned?
![截屏2023-06-17 07 11 31](https://github.com/dortania/bugtracker/assets/53130008/cb0b53c1-2a13-4523-b6f4-a7d8fa2e1d29)

**Comment by khronokernel** [comment]
> Is there any thing not to be mentioned?

Just take 2 seconds to look at the PR:
> This PR is not functional outside of members enrolled in the DortaniaInternal program

* https://github.com/dortania/OpenCore-Legacy-Patcher/pull/1077

----------

Please put the faintest bit of effort before filing issues, this is **not** a bug tracker for OCLP:

> This bugtracker is not for OpenCore Legacy Patcher, see respective support section listed in [project's README](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/README.md).
* https://github.com/dortania/bugtracker
