### ISSUE TITLE
macOS Sonoma Broadcom Wifi Crashes Some App

### ISSUE THREAD

**Issue by wqhqq1** [dortania/bugtracker#337]
- I've used OCLP to enable it
 - It works well in continuous feature
 - Most time it works well surfing the Internet
 
BUT THE PROBLEM:
When using some chromium based app like WeChat or DingTalk, it just crashes. and there's even NO but report window.

Could you please analyze where the problem is?

**Comment by exgphe** [comment]
Some Chromium based apps will crash if you set -amfi=0x80. I’m currently using AMFIPass.kext with -amfipassbeta and it’s working fine.

**Comment by wqhqq1** [comment]
So much appreciation!
I will try it later when I'm back home.

**Comment by wqhqq1** [comment]
[config.txt](https://github.com/dortania/bugtracker/files/12767851/config.txt)
@exgphe Sorry but I got dark screen after using AMFIPass.kext, any solution?

**Comment by exgphe** [comment]
> [config.txt](https://github.com/dortania/bugtracker/files/12767851/config.txt) @exgphe Sorry but I got dark screen after using AMFIPass.kext, any solution?

Remove amfi=0x80

**Comment by wqhqq1** [comment]
@exgphe If I remove it, I would get dark screen

**Comment by dhinakg** [comment]
This is not related to the guides. Please troubleshoot on the forums.
