### ISSUE TITLE
1366X768 HD4000 screen fix

### ISSUE THREAD

**Issue by LocTran016** [dortania/bugtracker#34]
Excuse me. I'm installing hackintosh on my DELL INSPIRON 3421 (MacOS Catalina 10.15.5 with OC 0.5.9 DEBUG) and I've suffered this for a long time because my laptop only have FB memory size=8mb so there is a way to modify the Capri framebuffer kext in oder to modify the FB memory size from 16MB to 8MB for fixing infamous screen garble when shutting down. There is a way to fix that: https://osxlatitude.com/forums/topic/11004-e6230-upgrade-to-mojave-has-anyone-had-success/page/2/?tab=comments#comment-90011 (I've get this from a man in Insanelymac.com) but it's for Clover but I think it may work on Opencore, too (just change something in the config.plist to patch that Capri frambuffer kext so I think there's still a use for that in Kernel->Patch) so I think that if it's possible, can you add it as a help for other people in your Troubleshooting page and in the sample.plist as well. Anyway, thanks a lot for reading my message
P/S: I've fixed it, no noise and garbale screen now so I want to share it with everone and here is my patch. So if it is possible, can you add this in the troubleshooting page. Thanks a lot for reading my message.
![image](https://user-images.githubusercontent.com/64778285/87237229-8d412400-c3a8-11ea-8576-f17352d757b8.png)

![DSC04355](https://user-images.githubusercontent.com/64778285/87237218-6c78ce80-c3a8-11ea-9054-44451625ad09.JPG)

![DSC04356](https://user-images.githubusercontent.com/64778285/87237214-68e54780-c3a8-11ea-96f0-f481790f523f.JPG)
![DSC04354](https://user-images.githubusercontent.com/64778285/87237217-6b47a180-c3a8-11ea-9ca5-cc4fe11cb741.JPG)

**Comment by khronokernel** [comment]
Hi, is there a specific reason not to use WhateverGreen's stolenmem patches? Would make patching much cleaner and universal to more platform IDs

**Comment by LocTran016** [comment]
![image](https://user-images.githubusercontent.com/64778285/87263569-6ea75f80-c472-11ea-92eb-51f16b3e8835.png)
I've try this but can't get any output

**Comment by LocTran016** [comment]
I going to use this soon
![image](https://user-images.githubusercontent.com/64778285/87263759-f55c3c80-c472-11ea-9c65-2c27ea60816c.png)

**Comment by LocTran016** [comment]
I've tried this also but the problem haven't been fixed.
![image](https://user-images.githubusercontent.com/64778285/87264690-803e3680-c475-11ea-8358-84cd39bb8da1.png)
