### ISSUE TITLE
Suggestion: add UHD630 sleep back screen problem to Coffee Lake Guide

### ISSUE THREAD

**Issue by luvletter2333** [dortania/bugtracker#35]
My specification: 
Dell Vostro 3670
i5 8400+UHD 630
Catalina 10.15.5 (framebuffer patched)

The problem has been put forward and solved here: https://www.tonymacx86.com/threads/intel-uhd-630-sleep-monitor-problem.296358/

add `igfxonln=1` to boot-arg to fix black screen from sleep

Please consider adding this problem to the Coffee Lake Guide.
Thanks!

**Comment by luvletter2333** [comment]
Oops. I suggest this tip being added to https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/coffee-lake.html#pciroot0x0pci0x20x0

**Comment by khronokernel** [comment]
This was already mentioned in our sleep troubleshooting guide and in the troubleshooting page:

* https://github.com/dortania/OpenCore-Desktop-Guide/pull/56
* https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#stuck-on-or-near-ioconsoleusers-gioscreenlockgiolockstate-3

The desktop guide should be transitioning to the new post-install site soon
