### ISSUE TITLE
OpenCore can't download installers

### ISSUE THREAD

**Issue by johnstonesnow** [dortania/bugtracker#351]
Hi, 
I am running OSX 10.15.17 on a late 2013 27" imac. I've just learned about OCLP and followed the excellent instructions here: https://dortania.github.io/OpenCore-Legacy-Patcher/INSTALLER.html#creating-the-installer

However I hit a major problem early on. I can't download installers. When I click to download I get constant errors:

"Error - Failed to download installer Catalog from Apple"

I have a perfectly good and very fast connection. I have no firewall issues. 

I have no idea how to use github, I tried to open an "Issue" on the main github page for OCLP but it said I can't as I am not a contributor to the project. I followed a few links and found this page so I opened an issue here. (I did look but couldn't find any other contact details for the developers or OCLP). 

Grateful if someone could comment on whether this is a known issue, or worst case, just point me towards a way to grab a Venturer installer from somewhere else to bypass the issue. 
thanks

**Comment by JochenVDP** [comment]
I have the same issue. And I used the same OpenCore-patcher just 5 days ago on a very similar Macbook, over the same network connection. So it looks like it might be Apple itself that says "no" to any request to download an installer using OpenCore?

What I'm trying right now is to download the needed installer directly. Found them all on mrmacintosh.com...

**Comment by johnstonesnow** [comment]
Thank you. Glad to hear it's not just me. I detest Apple. I'll do as you suggest, thanks again

**Comment by JochenVDP** [comment]
Update; DON'T TRY IT WITH AN INSTALLER YOU DOWNLOADED DIRECTLY

I tried this, while following the process on YT (https://www.youtube.com/watch?v=D8djeFJ1czU) and what I get was different than what I got with my other Mac (where the upgrade via OpenCore worked). 

To explain in detail; 
- I'm on Yosemite so to get to Sonoma I need to first upgrade to monterey, then to Sonoma (as the latter needs at least High Sierra to start from). So I have to go through that upgrade process I'm following on YT twice. The process is 100% the same with each upgrade though.   
- So I first downloaded the InstallAssistent.pkg and unpacked it in /applications (as that's where the OC patcher looks for it)
- I instructed the OC patcher to use an existing installer and it found the one that I downloaded myself. 
- The OC patcher skips a few steps compared to the YT vid (the download, validate & extract steps), but as of 2:30 (creating the OS installer) the process is the same again.
- All was going well until 4:37 in the video. I do not get that screen. Instead I get a screen asking me my choice of OS language. This is AS IF I'M FRESHLY INSTALLING MONTEREY. In other words; I think if I would have continued here I would have lost all my existing files and emails.
- So I took out the USB and rebooted the laptop. Luckily it came back to it's regular Yosemite desktop.

**Comment by johnstonesnow** [comment]
Wow, thanks. I hadn't actually started thankfully. However I really have no clue how this all works yet anyway. 
So are you saying OCLP process runs an update rather than a fresh install? I am planning on a fresh install. I have already cloned my files to a backup drive so my internal drive is wiped clean. Can I still use OCLP for a fresh install? If so, can I go straight to Ventura (as that's what I had planned/hoped to do)?

**Comment by JochenVDP** [comment]
It's actually the inverse; looks like OCLP wants to freshly install Monterey (that's the OS I downloaded). It wasn't giving me the option screen like on 4:37 of the YT video. I want to upgrade while keeping my files and emails, so I aborted the process there.

If you want a fresh OS you could decide to continue. But basically the rest of the process on the YT video may be irrelevant. The upgrade (or rather; install) process may be quite different and I'm not sure of the outcome. Basically the screen I got resembled the screen he got at 7:56. Which is weird as normally you get that screen after the major portion of the upgrade/install process ...but I got that screen immediately, at the start of the process.

Spooky, to say the least.

**Comment by johnstonesnow** [comment]
I suspect I'm not following as well as you think, but what makes you say "spooky"? I am intrigued! 
I don't fully understand how OCLP works. Does it modify the installer? If so, surely we can't use one downloaded from somewhere else?
I want to get into this right now and see if I can salvage more years of life out of TWO imacs! So I think I need to understand things a bit better (although my data is safe whatever happens, I was going to Linux until I heard about OCLP)

**Comment by JochenVDP** [comment]
Well what I mean is if you follow his video; as of 4:36 that install or upgrade is doing plenty of things (including a couple of reboots) until at the very end he goes "badda boom badda bing the new OS is installed and it's asking me for some settings" ...while my install or upgrade didn't do anything and didn't need reboots but immediately came to the first settings screen where I had to choose a language.

**Comment by JochenVDP** [comment]
By the way I left a comment on the video as well as I'm curious what Anson thinks about our issue.

**Comment by johnstonesnow** [comment]
Ah I see, yes very odd that. 
I am going to see if I can do a fresh install of Ventura using a downloaded installer. Here goes nuthin! :)

**Comment by JochenVDP** [comment]
Wishing you good luck!

**Comment by johnstonesnow** [comment]
Hmm. I am using the video you referred to. 
I have a Ventura installer. I built the USB installer properly and everything went well. 
Just connected it to my 2014 iMac, powered on holding ALT key, but it doesn't show up. There's only one option "Internet Recovery". 
Is there some trick I don't know about? I've booted from alternative boot drives before, never seen it fail to show the USB like this

**Comment by johnstonesnow** [comment]
PS in case relevent, I built the installer on a different iMac. This one has been wiped (hard drive formatted). I assume it should still see the USB installer on an ALT - boot?

**Comment by JochenVDP** [comment]
No idea. TBH I'm not that tech savvy myself. But you did give me a good tip; gonna try making that USB boot disk on my other mac. See if I get the original error there as well...

**Comment by JochenVDP** [comment]
OK that is really weird. On my other Mac the OC patcher was able to retrieve the MacOS installer list. Huh.

**Comment by johnstonesnow** [comment]
It gets weirder and weirder. I wonder if it's some sneaky Mac thing. I use a VPN all the time, so I assumed that's why my download failed. I have stopped using Apple email now because they have a clear prejudice of VPN users and repeatedly LOCK my entire account (even though I use the same IP all the time, albeit a VPN one). I am sick to the back teeth of Apple. If it wasn't for my hardware being damn good and having plenty of life left, I'd be on Linux. In fact, since I can't get this installer to detect on an ALT Boot, I may just be forced to try Fedora on this iMac. I tried it on a Macbook Pro a while back and it ran lovely, way faster and no 'telemetry' or processes analysing my photolibrary, installed apps, pulse/retina.... :)

**Comment by JochenVDP** [comment]
I'm actually on Linux Mint. The Macs I'm trying to upgrade is my old laptop (succeeded) and my wife's (struggling). 

To be fair Linux isn't perfect either. I got issues with hibernation, and the advice is to go to a higher kernel but when I do that my network is gone (wifi and LAN, so it's a hardware/driver issue). So I had to downgrade again.

And then I have trouble finding alternative softs than the ones I use daily. GNU is OK, almost Photoshop-like, but less intuitive. No alternative for my website building soft RapidWeaver, nor for iTunes... even editing PDFs is a mission.

**Comment by johnstonesnow** [comment]
Ha, you sound like my twin! I have been through the mill, learned a lot in process though. First big lesson was to buy a laptop that is fully supported on Linux. I spent months trying to get a macbook to run Linux, succeeded (kind of) in the end but it was just stupid, so I ditched the Macbook and got a PC and it's way better. 

I then chose a laptop that isn't perfectly linux compatible, so had more stuff to learn/fix. 

Fedora is bloody superb. I tried Mint (and many others) but none of them are (in MY opinion!) as friendly as Fedora, especially when coming from a Mac. The support is incredible on AskFedora forum (just incredible, everyone helps and answer in minutes, better than paid apple support!). After getting used to a few major differences I actually enjoy it more than I enjoyed Apple (and that's after 20 years on Apple!)

I just hate waste and refuse to throw out two perfectly good iMacs, so I am determined to give Apple a big fat middle finger and do some GOOD for the world, something they preach from their high horse continuously about doing, meanwhile doing the exact opposite. Apple, all about Privacy. Yeah, sure. So they coded G apps into iphones for BILLIONS in payment. Screw them, I had the scales lifted from my eyes a few years back and finally managed to worm my way out of the detestable Apple ecosystem (where THEY choose what I can and can't install, ban stuff from App store for political reasons, and so on). I don't need a nanny, I don't need Marxist indoctrination (least of all from hyper-capitalist hypocrites), I need an OS that I am the owner of and can use as I see fit. Sadly these days that means Linux and only Linux. Shame, I still like Apple's hardware, but my Lenovo Yoga 16" is a pretty sexy beast too :)

**Comment by JochenVDP** [comment]
Hah. You ARE my twin!

Almost exact same story here. Disappointed with Apple; they not-so-gently push you to new devices by making progs look less useable. We noticed this on our phones as well as our laptops. Like the browser no longer displaying websites correctly. Plus they get ever more expensive. While I was an IT guy in Europe; that was no problem. But now that I own and run a lodge in South Africa; I think twice before spending my hard-earned money. So I bought a nice Samsung laptop and tried a few linux flavors. The fiirst tries gave me too much trouble, but Mint ran fine so I stuck with it. Well, I'm also an ex unix admin so to be fair linux is like a walk in the park for me ...most of the time. Of course; the OS might be great but the available softs.... ay ay ay.

Anywayy my mss loves her macbook hence why I try upgrading it now. And the painful thing is; the upgrade worked fine on my old mac, but not (yet) on hers. I just made that install USB on my mac. Gonna try it on her mac, later today. Fingers crossed.

**Comment by dhinakg** [comment]
This is not a bugtracker for OCLP. The OCLP issue tracker is closed to new issues. If you need support with OCLP, go to the [OCLP discord](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main?tab=readme-ov-file#support).

**Comment by johnstonesnow** [comment]
> Hah. You ARE my twin!

Weird! I was an IT guy about 25-30 years ago, got sick of office environment so I buggered off to different things (now farming! :D) Good luck with it, I actually find the apps on Fedora/Linux WAY better than Mac, ONCE You find em!! I love the fact they are free, don't try to upsell you, don't try to steal/harvest your data for marketing BS, and above all, don't come with the Apple premium (both arrogance as well as price!). 

Example - Mac Mail user for 20 yrs. Finally tried that orrible Thunderbird thing, ok it feels less 'pretty' and a bit dated (though there are other prettier ones, Evolution for example, but I need a stack of local folders so Thunderbird it is). After the pain of having to read the manual, set stuff up etc, it's WAY more powerful, actually finds what I want when I search all mail, can have all sorts of complex rules and filters, it's just far more effective for me. Same goes for a ton of others things. 

I used Little Snitch for years (hence why I detest Apple and their telemetry (spyware) BS). It cost me a pretty penny and I refuse to spend out again (which I will have to once I update the OS). Then I found OpenSnitch, a 'fork' of Little Snitch for Linux, I can't wait to use it! (So I can control EVERY connection made by installed apps AND the operating system). So i can have a functional app, but can politely (or rudely) decline that they feed my activity/IP etc to Facebook, Google etc.  

Back to the point...
 

> This is not a bugtracker for OCLP. The OCLP issue tracker is closed to new issues. If you need support with OCLP, go to the [OCLP discord](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main?tab=readme-ov-file#support).

I've heard of Discord but never used it. I'll take a look thanks.

**Comment by JochenVDP** [comment]
Yup. You're my brother from another mother all right. I do run Little Snitch on my macs too haha.

And Thunderbird on linux; indeed better than Mac Mail. It's just that for some stuff I can't find a decent alternative on Linux ...yet.

On topic; I made a OC Monterey boot drive using my other Mac, Then used that one on the other mac  (the mac that showed the initial issue as described in the 1st post of this thread). And I got exactly the same result as described somewhere half way this thread; instead of getting a selection screen like at 4:37 of that YT video, I get a language selection screen. As if Monterey will just be installed anew, without keeping existing user environment. Scary and disappointing.

Will look for a solution, but not keeping my hopes up.

**Comment by johnstonesnow** [comment]
I don't want to try helping as I'm not qualified really. Yes it does SOUND like you've lost all your data and it's doing a fresh install, but that MAY not be the case, maybe the next screens will allow you to preserve/import your old data. I guess in your shoes I'd be deciding whether to force shutdown and reboot to see if any of the old system is still there, OR push on through and hope for the best. Not sure how much data we're talking about. I had around 1TB of important data so I took a carbon copy clone (TimeMachine would have been fine also), i always do fresh installs and then import data, old habits i guess. 

My advice at this point would be to try joining that support/user community and ask in there, if you haven't already. I don't think we're gonna get any help anywhere else. I'll be watching though and wish you luck with it

**Comment by JochenVDP** [comment]
Well I decided to abort & reboot. System still as is. It's my wife's laptop. She doesn't want to lose any files. I suppose I could back up everything & then proceed. But that's going to be a mission in itself.

**Comment by johnstonesnow** [comment]
Hiya. Honestly, piece of cake!

Firstly, how much data does she have? Is it APPS, or just data like pictures, documents, music, videos etc?

If she has loads of apps and you want to retain all the settings etc, that needs a backup which is dead easy if you can just find a USB hard drive (I get em used on ebay but not sure if that's possible where you are, do you have any spare HDDs?) I'd just let TimeMachine back it all up, format the HDD and point TM at the drive and wait for it to complete. I use Carbon Copy Cloner to do similar, but it makes a bootable drive which is handy to pull files off backups and boot from it when needed. 

If all she has is the usual files in home folder, I'd just get a big USB stick (cheap on amazon now) and drag and drop to the stick all her pics and files. That will do, can drop them back in same folders after you've installed new OS. 

Once I had the installer I found OCLP so easy. Don't panic if it doens't look like the YT video, mine didn't either, but worked perfectly. I've decided I am leaving Apple completely so I doubt I'll be using this machine, but wanted to confirm OCLP works and it sure did. I did make a  mistake though, you MUST choose the correct model (using the funny model numbers from Apple, like 14,2 (comma) in my case). Once you tell OCLP app what version you're building an installer for, and you have the installer downloaded, let it run and you can get her machine running whatever OS you want. 

I think you'll be fine, especially now you know you didn't lose her files :)

**Comment by JochenVDP** [comment]
Thx 4 the tips. I did take backups of all her folders and mail accounts, but still: it freaked me out that OCLP screens were different.

But now I received a clue as to why they are different (via Reddit); apparently my wife's macbook can be upgraded to Monterey the regular way! Perhaps that is why the OCLP tool didn't give me any installers in the first place. And why, when I still insist in using it, it's not giving me the screens as expected.

**Comment by johnstonesnow** [comment]
Aaah, yes that might be the reason. I couldn't get installers so I think that's probably Apple trying their best to stifle any way to get around their sabotage of old hardware!
