### ISSUE TITLE
Where is the community?

### ISSUE THREAD

**Issue by johnstonesnow** [dortania/bugtracker#352]
I read the page at https://dortania.github.io/OpenCore-Legacy-Patcher/

I spotted this: "Whether it's getting started or learning the specifics, you can always find answers with our amazing community of tinkerers, developers, and dreamers."

Tell me, where can I find this amazing community, or even a lacklustre one please!

**Comment by dhinakg** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main?tab=readme-ov-file#support
