### ISSUE TITLE
New Discord CDN rules break links

### ISSUE THREAD

**Issue by run4r-ses** [dortania/bugtracker#353]
the links for XLNCUSBFix.kext and AMD StopSign-fixv5 kexts are dead because Discord introduced a new CDN system. the files should be uploaded to GitHub or some sort of platform for preservation.

this problem affects all cdn.discordapp.com links in this repo

example: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#usb-issues

**Comment by ghost** [comment]
As a workaround you can send these links to a Discord text channel/DM, right click, and then `Copy Link`. The client will add the required parameters (`ex`, `is` and `hm`) to the URL and you should be able to download the files. For example, here's both of these kexts:

[XLNCUSBFix.kext.zip](https://github.com/user-attachments/files/15905120/XLNCUSBFix.kext.zip)
[StopSign-fixv5.zip](https://github.com/user-attachments/files/15905138/StopSign-fixv5.zip)

**Comment by hkusdaryanto** [comment]
this issue can be close per https://github.com/dortania/OpenCore-Install-Guide/commit/9aca3395e04c406afad9e17b63e5e60cde6de7d2
