### ISSUE TITLE
SMBIOS for Intel Coffee Lake

### ISSUE THREAD

**Issue by HQuest** [dortania/bugtracker#36]
https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/coffee-lake#platforminfo

While the original rationale to select a SMBIOS for an Intel Coffee Lake processor is the processor itself, by setting up OC to  present a SMBIOS of an Apple device that has no dGPU when your system does have a dGPU causes issues with DRM/AppleGVA component. In such cases, if the user do want to make use of online video services such as Netflix, Amazon Prime or the own AppleTV+, they are better selecting a system that natively has a dGPU - i.e., an iMacPro1,1 instead of the iMac19,x. Failure to do so causes the AppleGVA component not to initialize properly and fail to reproduce videos. In either scenarios, assuming the configuration is correct in other components, both H.264 and HEVC video processing would be enabled with Encoding/Decoding supported via Hardware (as seen on tools such as VideoProc); in other words, fully hardware accelerated.

If there is no dGPU or the user does not make use of any online video streams, then yes, the iMac19,x SMBIOS would make it more akin to the real Apple hardware.

**Comment by khronokernel** [comment]
Why change the SMBIOS to one with incorrect power stepping and such when you could use WhateverGreen's board-id swapping as mentioned in the DRM Guide?
https://dortania.github.io/OpenCore-Desktop-Guide/post-install/drm.html

**Comment by HQuest** [comment]
Maybe because 1) the DRM guide fix is broken for most recent systems [1], 2) this fix might not be supported going forward [1] and 3) you can always generate a P/C states SSDT table to have SpeedStep fully working (still assuming a supported hardware).

[1] https://github.com/acidanthera/bugtracker/issues/1034

**Comment by khronokernel** [comment]
> the DRM guide fix is broken for most recent systems

That's a beta...
Vit still has around 4 months to resolve user-space patching, I'd rather not base the guide off of what *might* happen. When Big Sur's official launch comes around, we'll obviously reconsider but the changes with KC has a lot of info up in the air.

> you can always generate a P/C states SSDT table to have SpeedStep fully working (still assuming a supported hardware).

What about the X86PlatformPlugin vectors? Of course you can override them manually but using a Xeon based SMBIOS with a consumer CPU can cause wake issues like `Sleep Wake failure in EFI`, seems like adding more work arounds for something that can be resolved initially with WEG's patches. 

Appreciate you opening the issue, but we've been talking with Vit and others for quite some time so we know about these issues with Big Sur. So we'll revisit this issue in the fall
