### ISSUE TITLE
acpi-wake-type on USB controller doesn't work

### ISSUE THREAD

**Issue by TraskIT** [dortania/bugtracker#37]
Hello,
i'm experiencing the second-press keyboard to wake display bug.
I tried both the solutions on USB Guide (acpi-wake-type property on USB controller and USBWakeFixup kext + ssdt) but the problem is still here.
What can i try?
Tell me if i have to attach some log, efi folder or ioreg (and if i wrote this issue in the right place).

I have a Ryzen 5 2600 and a Gigabyte B450 aorus pro if that matters (This configuration has the XHC0 sleep kernel panic bug, i managed to resolve that with removing any device attached to these ports) 

Thanks in advance

**Comment by khronokernel** [comment]
Might be worth looking at Darkwake values and trying different combos. I just added a third section on it you can read about:
* https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html#method-3-configuring-darkwake

If that doesn't work, you can comment but we're likely not going to delve any deeper into wake issues. However if you do find a proper fix, we're more than happy to add it
