### ISSUE TITLE
[Guide added] Stuck On the UEFI booting LOGO or `OC: Connecting drivers...` or `HdaControllerInitPciHw(): controller version 0.0`

### ISSUE THREAD

**Issue by sky5454** [dortania/bugtracker#38]
We require the following for guide issues:
## new Guide 
* Booting Issues:
  - Stuck on the motherBoard's UEFI booting LOGO
      ![image](https://user-images.githubusercontent.com/12370628/87772265-11d1ed80-c854-11ea-9066-a004c271a4ea.png)

  - Stuck on `OC: Connecting drivers...` , see _log A_
  - Stuck on the `HdaControllerInitPciHw(): controller version 0.0`, see _Log B_

_Log A:_
```log
12:906 00:231 OCABC: MAT support is 0
13:194 00:287 OC: Driver OpenRuntime.efi at 4 is successfully loaded!
13:431 00:236 OC: Driver PartitionDxe.efi at 5 is being loaded...
13:676 00:245 OCABC: Recovering trashed GetMemoryMap pointer
13:914 00:237 OC: Driver PartitionDxe.efi at 5 is successfully loaded!
14:159 00:244 OC: Driver PartitionDxe.efi at 5 needs connection.
14:406 00:247 OC: Connecting drivers...
------End of this log
```
_Log B:_
```log
12:906 00:231 OCABC: MAT support is 0
13:194 00:287 OC: Driver OpenRuntime.efi at 4 is successfully loaded!
13:431 00:236 OC: Driver PartitionDxe.efi at 5 is being loaded...
13:676 00:245 OCABC: Recovering trashed GetMemoryMap pointer
13:914 00:237 OC: Driver PartitionDxe.efi at 5 is successfully loaded!
14:159 00:244 OC: Driver PartitionDxe.efi at 5 needs connection.
14:406 00:247 OC: Connecting drivers...
14:561 00:154 HDA: Starting for C84D5298
14:860 00:299 HdaControllerInitPciHw(): controller version 0.0
------End of this log
```

**Reason**
three problems are all the same reason: The Driver are not suitable for the machine.
**NOTE**: AMD GPU also has a Audio module, don't not add a `AppleALC` before macOS installed, for `AppleALC` may not suitable for AMD GPU's Audio module. More see: The supported list of `AppleALC` in [Supported-codecs_WIKI_AppleALC](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)

**Solution**
remove the Drivers who stop the process of OC booting. under `UEFI - Driver` in config.plist
relating to [Haswell](https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/haswell.html#drivers)

<hr><br>

## How I find and solve it
 > Here is detail
### at the beginning
I boot OC , but couldn't see OC's picker.
It is stacked on the  motherBoard's UEFI booting LOGO.
 ![image](https://user-images.githubusercontent.com/12370628/87772265-11d1ed80-c854-11ea-9066-a004c271a4ea.png)

### Debug
Then I replace the  OpenCore and Driver 's `The Released Version` to `the Debug Version` trun on [the highest level of logs](https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/debug.html)

I found it stack on the  `HdaControllerInitPciHw(): controller version 0.0` 
> if the log level is not highest, you may only see it stack on `OC: Connecting drivers...` 
```log
12:906 00:231 OCABC: MAT support is 0
13:194 00:287 OC: Driver OpenRuntime.efi at 4 is successfully loaded!
13:431 00:236 OC: Driver PartitionDxe.efi at 5 is being loaded...
13:676 00:245 OCABC: Recovering trashed GetMemoryMap pointer
13:914 00:237 OC: Driver PartitionDxe.efi at 5 is successfully loaded!
14:159 00:244 OC: Driver PartitionDxe.efi at 5 needs connection.
14:406 00:247 OC: Connecting drivers...
14:561 00:154 HDA: Starting for C84D5298
14:860 00:299 HdaControllerInitPciHw(): controller version 0.0
```

obviously, the version of HDAController must not be `0.0`.
 so I use another Haswell machine to test, its log has nothing wrong and work well.
You can see its HDAController version is `1.0`
```
16:617 00:345 OC: Connecting drivers...
17:016 00:399 HDA: Starting for C657BF18
17:278 00:261 HdaControllerInitPciHw(): controller version 1.0
17:587 00:308 HdaControllerInitPciHw(): capabilities:
  64-bit: Yes  Serial Data Out Signals: 0
17:864 00:277   Bidir streams: 0  Input streams: 0  Output streams: 2
18:220 00:356 HdaControllerGetName(): controller is Intel Ivy Bridge/Haswell HD Audio Controller
18:650 00:429 HdaControllerInstallProtocols(): start
19:027 00:376 Gotten here
---lots of log behinds
```

## Solved
I see the  [Haswell](https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/haswell.html#drivers), it say only the  `HfsPlus.efi` and  `OpenRuntime.efi` should be load, and others should be removed.
So, I removed `AppleALC`, then work.
~~<string>AudioDxe.efi</string>~~

## Analysis the cause
the machine that failed has a AMD GPU, and after I pull out the graphics card and load the AppleALC, it also work .
I guess AMD's dGPU has Audio module which AppleALC not supported, and fact as it: [Supported-codecs_WIKI_AppleALC](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)

**Comment by dhinakg** [comment]
Uh, what? AppleALC has no bearing on hang issues occurring during OpenCore boot. I think you mean AudioDxe, and last I checked, that driver wasn't recommended for use in the guide anyways.

AppleALC itself does not have issues with AMD dGPUs, I use it for digital audio just fine. (I might be confused with WhateverGreen on which enables digital audio, but I have both and there is no issue)
