### ISSUE TITLE
Opencore-install-guide-translation

### ISSUE THREAD

**Issue by LocTran016** [dortania/bugtracker#41]
Excuse me, I want to make a translation of your guide and do you feel free to let me use your themes in the .vuepress folder (I'll write that it is from you). Thanks for reading this

**Comment by khronokernel** [comment]
Hello, anyone's free to translate and rehost our guide with proper credit and licensing. This page should clarify a bit: https://dortania.github.io/OpenCore-Install-Guide/CONTRIBUTING.html
