### ISSUE TITLE
Fixing CFG-Lock

### ISSUE THREAD

**Issue by LocTran016** [dortania/bugtracker#42]
#VerifyMSRE2
Excuse me, can you please add a picture of what shown on the screen or the log after select the VerifyMSRE2 option in the picker 
on a laptop which its BIOS supports CFG-Lock and if it can be unlocked.
![image](https://user-images.githubusercontent.com/64778285/87887209-46f56000-ca4d-11ea-9380-ea1af187b75f.png)
Many thanks for reading my message

**Comment by dreamwhite** [comment]
If your firmware has unlocked MSR 0xE2 you should see something as the depicted one below:

![image](https://user-images.githubusercontent.com/17933708/89450837-83b69c00-d75b-11ea-8bf3-e74bba9311f1.png)

For more infos about how VerifyMsrE2.efi works, check it out [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Application/VerifyMsrE2/VerifyMsrE2.c#L92-L95)
