### ISSUE TITLE
Necessary DSDT Fixes / Missing Documentation?

### ISSUE THREAD

**Issue by Chilluminati91** [dortania/bugtracker#43]
I am currently following your brilliant guide for the 4th time on a different machine. Had no problems until now.
It seems like this device specifically (Matebook X Pro 2020, i5-10210U) needs certain modifications that are not documented anywhere.
I succeeded with other Comet Lake Models where I am failing now and wonder if I'm supposed to patch the DSDT before I can even reach the installer and if so how?

OpenCore and Clover both have problems with the HWEC device and specifically the method ECRD (Battery related).
Verbose Output that repeats endlessly (and occasionally freezes):

```
Initialized Local Variables for method [ECRD]: 
Local0: ffffff8034b31280 <Obj>                Integer 0000000000000000 
Initialized Arguments for Method [ECRD]: (0 arguments defined for method invocation) 
Arg0: ffffff8035179550 [Ref0f] <Node> Name ELUX Uninitialized 


ACPI Error: Method parse/execution failed [A_SB.PCIO.LPCB.HWEC.ECRD] (Node ffffff8035019c60), AE_AML_NO_RETURN_VRLUE (20160930/psparse-632) 
ACPI Error: Method parse/execution failed [\_SB.PCIO.LPCB.HWEC._QA8] (Node fiffff8035019000), AE_AML_NO_RETURN_VHLUE (20160930/psparse-632) 
ACPI Error: Result stack is empty!       State=ffffff8035172810 (20160930/dswstate-182) 
ACPI Exception: AE_AML_NO_RETURN_VHLUE, Missing or null operand (20160930/dsutits-775) 
ACPI Exception: AE_AML_NO_RETURN_VHLUE, While creating Arg 0 (20160930/dsutils-902) 

[ECRD] @00031 #0070: Local1 = -Return Value- () 
```

I attached my extracted ACPI and EFI.

[ACPI Extracted.zip](https://github.com/dortania/bugtracker/files/4948503/ACPI.Extracted.zip)
[EFI.zip](https://github.com/dortania/bugtracker/files/4948506/EFI.zip)
![Verbose](https://user-images.githubusercontent.com/47525435/87953682-a5e9c200-caab-11ea-964c-0f4e47823de4.jpg)

**Comment by khronokernel** [comment]
The above ACPI errors are due ACPI issues with your battery, for install we recommend removing `SMCBatteryManager.kext` and then patching you battery properly as mentioned here: 
* https://dortania.github.io/OpenCore-Post-Install/laptop-specific/battery.html
