### ISSUE TITLE
Cannot Disable dGPU.

### ISSUE THREAD

**Issue by DilVika** [dortania/bugtracker#45]
Hello, I have moved from Clover to Opencore for few days. 
My System: **Asus GL552VX (laptop)**
**Intel core i5 6300HQ** 
**HD530 + NVIDIA GTX950M (Optimus).**
Now I found that the dGPU is not completely disabled when I use **-wegnoegpu**. Then I tried to follow the tutorial 
**[Disabling laptop dGPUs (SSDT-dGPU-Off/NoHybGfx)](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html)**. 
But The dGPU seem like still pulling power (by cause heat and showed in Hackintool's PCI tab) (It didnt happen when system is on Clover).
I am sure that the dGPU's address was corrected. Please check it, and tell me how to fix or any solution. 
Thank you.

![Screen Shot 2020-07-23 at 08 01 45](https://user-images.githubusercontent.com/41282771/88243497-c471d800-ccba-11ea-8e32-343d0d997a23.png)
[report_dGPU_problem.zip](https://github.com/dortania/bugtracker/files/4963384/report_dGPU_problem.zip)

**Comment by khronokernel** [comment]
In the above EFI, you did not include `-wegnoegpu`. If macOS identifies the device as a GPU then the SSDTs do nothing.
If the issue still persists with the boot-args, you can reopen the issue but I would ask if you could provided the known working Clover EFI as well

**Comment by DilVika** [comment]
Even when using `-wegnoegpu` (with or without), dGPU still pulling power (by heat (higher than using with clover's about 5 - 6 *C without CPU higher 

usage) and It will not show in PCI tab like the picture); but sometimes, when I do an hot boot (after shutdown from windows) the heat problems not happen).
I attached Clover EFI bellow. It's not made by me, but seem like disabling dGPU well (except waking from sleep, the dGPU will turn on again).
[Clover.zip](https://github.com/dortania/bugtracker/files/4974179/Clover.zip)

**Comment by DilVika** [comment]
**Update: ** After some tweak (I don't rememeber exactly), the problem has gone. I am going to continue researching on it, if I found something useful, I will suggest an improving on guide. 
Thank for you supporting. :D

**Comment by DilVika** [comment]
**Update** : Hello, After some change, I found that without GPIO patch (GPIO.aml), the problem has gone, but when I enabled GPIO.aml again. THe Problem comeback. Are there any suggestion please?
