### ISSUE TITLE
Laptop: Blackscreen on Comet Lake i5-10210u integrated display. USB-C HDMI working.

### ISSUE THREAD

**Issue by Chilluminati91** [dortania/bugtracker#46]
When booting into macOS via OpenCore (following Dortania Guide for Comet Lake) the internal Display either automatically turns off or has no iGPU acceleration, depending on the device setup. When having a blackscreen connecting an external monitor works, and GPU acceleration is visible. Some configurations let me boot with the internal display but they have no gpu acceleration.

Laptop: Huawei Matebook X Pro 2020
CPU: Intel i5-10210U
iGPU: Intel UHD 620
Monitor: 3k Touchscreen

Here is what I've tried so far:
- igfxcflbklt=1 boot argument
- AppleBacklightFixup.kext + applbkl=0 boot argument
- Patching Framebuffer-con0 to con3
- These device and platform-id combos: 
![List](https://user-images.githubusercontent.com/47525435/88468365-a4bcf880-cee2-11ea-8f45-805791d57551.png)

This is my OC Configuration:
[EFI.zip](https://github.com/dortania/bugtracker/files/4976928/EFI.zip)

And here is the bootlog (booting with suggested id's from Comet Lake section - no hw acceleration but monitor works):
[opencore-2020-07-26-014855.txt](https://github.com/dortania/bugtracker/files/4976929/opencore-2020-07-26-014855.txt)

**Comment by khronokernel** [comment]
Try `igfxonln=1` in boot-args, most likely an issue with AGPM where certain displays may not wake correctly

**Comment by Chilluminati91** [comment]
Sadly no difference. BUT I noticed (by building a Clover config) that my battery patch seems to be the source of the problem.
Booting with Clover and platform-id: 0500A53E and device-id: A53E0000 works with GPU acceleration and the internal display.

As soon as I add my patched DSDT GPU Accel and trackpad are not working anymore.
Even adding a vanilla DSDT causes the same problem, seems to be really laptop specific.
Will look into this. Thanks for taking your time!

On another note:
The link "Coffee Lake Plus and Comet Lake" in the table on this site leads to the Coffee Lake page, not the Coffee Lake Plus page:
https://dortania.github.io/OpenCore-Install-Guide/config.plist/#intel-desktop

**Comment by marianopela** [comment]
@Chilluminati91 I guess this is solved, according to your repo, right?
