### ISSUE TITLE
Use partial guide info

### ISSUE THREAD

**Issue by Juan-VC** [dortania/bugtracker#47]
I created a guide for my laptop and I was wondering if I could use partial information on the advantages of OC over Clover. 
Approval of Dortania icon usage would also be welcome for the guide.

Based my OC setup and guide site partially on the OC install guide which looks neat! Thanks in advance.

**Comment by khronokernel** [comment]
Oh I have no issue with you using our info, so long as proper credit is given. Regarding logo use, we'd like to keep that to Dortania guides only as to help users identify that it is in fact an official Dortania guide.

And thank you for reaching out, we quite appreciate it! Best of luck with your guide
