### ISSUE TITLE
alc-layout-id over layout-id

### ISSUE THREAD

**Issue by zhen-zen** [dortania/bugtracker#49]
In https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#making-layout-id-more-permanent, the priority for `alcid`, `alc-layout-id` and `layout-id` is listed. However, I think those explanation is not accurate.

In https://github.com/acidanthera/AppleALC/blob/9e1166c37b71e0ea286ca924c834adb33673723b/AppleALC/kern_alc.cpp#L206 the three properties are described. Here`alc-layout-id` "has normal priority and is expected to be used."

`layout-id` is actually what AppleHDA used for choosing different layout. However after a change in AppleHDA, some of the layouts are abandoned and old method of just replacing those resources (*.xml.zlib) no long works. AppleALC takes a workaround that provide single `layout-id` 7 to AppleHDA. Internally it transforms all id to 7 and only substitute  resources for layout-id 7 with patched ones. Then `alc-layout-id` came out to reduce confusion since the id is actually the internal ones used by AppleALC. And `layout-id` is also processed for compatibility.

So my suggestion is as follow:
2. `alc-layout-id` in DeviceProperties, replace `alcid` boot-arg after got an optimal id
3. `layout-id` in DeviceProperties, legacy support for non-Apple hardware, deprecated

**Comment by khronokernel** [comment]
Vit removed support for alc-layout-id in this commit for non-Apple devices:

* https://github.com/acidanthera/AppleALC/commit/d6cf2f004bc9032d59e9c2c96d8adb89f62a2426

We actually had a discussion around this time, as we previously linked to the AppleALC source when we used all-layout-id ourselves:

* https://github.com/dortania/OpenCore-Install-Guide/blob/e08ee8ebe6fa030393c153b055225f721edafab2/post-install/audio.md

**Comment by zhen-zen** [comment]
Sorry, it seems that I missed the changelog for that release. I should have read read the code right below the comment.
