### ISSUE TITLE
[Guide] Unlocking CFG Lock

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#52]
Hi there,
I'm opening this issue for teaching how to unlock CFG Lock for different motherboard vendors (laptops and deskies).
I know that there's your [guide](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html) but sometimes `setup_var 0xXYZ` command fails and you should try `setup_var2` or even `setup_var_3` command
At the moment, I've published a small guide for Dell motherboards, which you can read [here](https://github.com/dreamwhite/bios-extraction-guide/tree/master/Dell).
I'll upload in those days the other guides for other vendors.
Stay tuned :)

**Comment by khronokernel** [comment]
I currently don't have plans to expand the MSR guide anymore than it is now as I have more important guides to mainatin, however I've been adding external links to such a the RU thread on reddit:

* https://www.reddit.com/r/hackintosh/comments/hz2rtm/cfg_lockunlocking_alternative_method/

PRs are open but seems you've made your own guides. If it's alright, I'll likely add your guides to the MSR page so users can have a few more options. 
Just add a message here if there's other guide's you'd like to reference

**Comment by khronokernel** [comment]
Forgot to close this issue when we merged this PR:
* https://github.com/dortania/OpenCore-Post-Install/pull/20
