### ISSUE TITLE
[USB Mapping] USBMap vs OEM SSDT

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#53]
Hi there,
I've read your [guide](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html) about USB Mapping on Intel platforms.
I know that this is the fastest way to map USBs, but as explained in my [guide](https://utopiateam.gitbook.io/mammamia-marcello-vanilla-guide/post-installation/usb/mapping/intel) (sorry for broken images, need to fix them), the ACPI method should be considered.

What is the main advantage? 
- Independency from SMBIOS: USBMap creates a Info.plist file which maps the USB ports based off the current SMBIOS. If you change the SMBIOS you need to repeat this process, or even editing the Info.plist. Is this necessary? I feel it like frustrating.

Many thanks and feel free to suggest :) 
Have a nice day

**Comment by khronokernel** [comment]
So ACPI mapping was considered at one point, however the reason we didn't choose it was for a few reasons:

* ACPI in general is more complicated to the end user, and much more likely to break things in unintended ways both in Windows and macOS if done improperly. While some people may be comfortable with coding, most people I've met are not.
* How macOS enumerates ports doesn't always match how the ACPI tables look, it's more consistent on intel chipset controllers, but AMD and 3rd party sometimes have weird issues like PTXH showing up as PTCP ports. So this can easily spin you in circles when mapping.
* Dropping tables can remove other important info, such as how AMD may write the thunderbolt table mixed in with the XHCI table. And you also have the issue of USB ports being defined in the DSDT, as now we have another edge case where we inject a patched DSDT

I feel [Osy's ACPI tables](https://github.com/osy86/HaC-Mini/blob/master/ACPI/SSDT-Xhci.asl) are the ideal situation for USB mapping with ACPI, however there's too many edge cases to watch out for in the real world.

> Independency from SMBIOS

Simple 1 line change in the model section(or if you have multiple maps, change in entry entry), and tbh how many people change their SMBIOS regularly?

Hope this can clarify things a bit on our decisions with USB mapping
