### ISSUE TITLE
[ACPI] SSDT XOSI question

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#54]
Hi there,
I was analyzing [SSDT-XOSI](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-XOSI.dsl) and asked myself: where does those strings comes out? 
After doing my researches I've found this article, published on official Microsoft [site](https://docs.microsoft.com/en-us/windows-hardware/drivers/acpi/winacpi-osi).
My question is: do we need to add those strings inside your SSDT-XOSI or the ones provided are sufficient? 
Many thanks
Have a nice day :D

**Comment by dhinakg** [comment]
Generally the ones provided are sufficient, except for really recent laptops, which may need `Windows 2015` added (you can check in your DSDT). I don't expect any OEMs to be using anything after `Windows 2015` however.
