### ISSUE TITLE
[ACPI] Ivy Bridge Power Management should not drop tables

### ISSUE THREAD

**Issue by vit9696** [dortania/bugtracker#57]
If you drop the original power management tables, you will break power management (e.g. Turbo Boost) in Windows. It is clearly undesired. Instead of dropping the tables you should simply add the Apple power management ACPI methods `ACST` and `APSS` to the CPU scope, i.e. where the original `_CST` and `_PSS` methods are. I believe these methods are properly generated by the Piker's shell script.

**Comment by LocTran016** [comment]
Excuse me, I'm using Dell Inspiron 3421 and I have installed macOS 10.15.6 with OpenCore 0.6.0 release version
## My Dell Inspiron 14 3421 specs:
```
<CPU:      Dual-Core Intel Core i5-3337U (Ivy Bridge), 1800 MHz>
<MOBO:     Dell Inspiron 3421 (Chipset HM76)>
<RAM:      3993 MB (DDR3 SDRAM)>
<BIOS:     A13 (12/14/2015)>
<GPU:      Intel(R) HD Graphics 4000>
<Monitor:  LG Philips LP140WH2 (Dell MV65P) [14" LCD] (1366 x 768), connector LVDS>
<Audio:    Realtek ALC282>
<HDD:      WDC Green 500GB>
<Keyboard: Standard PS/2 Keyboard>
<Mouse:    Synaptic PS/2 Touchpad>
<Wifi+BT:  Dell Wireless 1704>
<Ethernet: Realtek PCIe FE Family Controller>
```
Like you have said above, when I'm using Window 10 LTSB 2016, the CPU power management working crazy, the turbo boost seem unstable, it go up to 2.60 GHz (my max turbo boost frequency) and then go to energy saver rengularly:
[Video_2020-08-12_223001.zip](https://github.com/dortania/bugtracker/files/5063754/Video_2020-08-12_223001.zip)
P/S: I'm really sorry for giving you a bad video with low resolution. Thanks for reading my message

**Comment by vit9696** [comment]
The solution is not correct.

Note, that sometimes adding the ACPI table that ssdtPRGen generated will not work, as it will make a conflict. To my memory, ssdtPRGen tries to detect whether operate on the `Scope` or add `Processor` objects with `_HID`, `_STA`, and so on. All this needs to be removed if that happened or ssdtPRGen needs to be rerun. `Processor` should be an external object, which one will inject Apple properties into, like this:

```
DefinitionBlock ("ssdt.aml", "SSDT", 1, "APPLE ", "CpuPm", 0x00021500)
{
    External (\_PR_.CPU0, DeviceObj)
    External (\_PR_.CPU1, DeviceObj)

    Scope (\_PR_.CPU0)
    {
        Name (APLF, Zero)
        Name (APSN, 0x04)
        Name (APSS, Package (0x20)
        {
            /*  … */
        })

        Method (ACST, 0, NotSerialized)
        {
            /*  … */
        }

        /*  … */
    }
```


Disabling table dropping is best to be moved to the end as a note, because for the newer readers it is irrelevant for the newcomers.
