### ISSUE TITLE
SSDT-RHUB leads to ACPI_BIOS_Error BSOD when booting Win10 via OpenCore

### ISSUE THREAD

**Issue by HarryHung** [dortania/bugtracker#59]
CPU: Intel® Core™ i7-10700K Processor
MB: ASUS Prime Z490-A
GPU: Sapphire NITRO+ RX 5700 XT 8G GDDR6 

Followed the Desktop Comet Lake Guide (using pre-built SSDT-RHUB):
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html

Both the OpenCore and MacOS works fine. However, when I try to boot into Windows 10 via OpenCore, it instantly shows a BSOD with the error message "ACPI_BIOS_Error". The Windows 10 installation works fine if booted directly (bypassing OpenCore)

Found this person on Reddit using ASUS TUF Gaming Z490 having the same issue:
https://www.reddit.com/r/hackintosh/comments/hsdbmd/acpi_bios_error_on_windows/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Removed pre-built SSDT-RHUB and now Windows 10 can boot fine via OpenCore. However, USB 2.0 ports stopped working in MacOS (which is used by the BT portion of FV-T919).

I think perhaps the pre-built SSDT-RHUB is not fully compatible with ASUS Z490 MBs as suggested by the guide?

**Comment by khronokernel** [comment]
I believe I know the issue, been meaning to get around to it. The prebuilt and source files omit a return value for non-darwin based systems and so it'll error out. Try this below SSDT:
[SSDT-RHUB.aml.zip](https://github.com/dortania/bugtracker/files/5081142/SSDT-RHUB.aml.zip)

**Comment by HarryHung** [comment]
Thanks for the prompt reply. I built the machine for a friend, so I don't have instant access to the machine at the moment. I will get back to you ASAP! Thanks a lot!

**Comment by HarryHung** [comment]
Finally got around to test it. It works perfectly. Now both Windows and Mac have full USB support. 

Thank you!
