### ISSUE TITLE
Small fix for time when dual boot macOS + Window

### ISSUE THREAD

**Issue by LocTran016** [dortania/bugtracker#60]
I don't know if you could add a small fix for the time in the OpenCore-post-install/Multiboot
Credit to:
* [Is there a fix for Windows changing its time when dual-booting with Hackintosh?](https://www.reddit.com/r/hackintosh/comments/6hx05v/is_there_a_fix_for_windows_changing_its_time_when/)
* [Fix Windows and macOS Showing Different Times When Dual Booting]( https://www.applegazette.com/mac/fix-windows-and-macos-showing-different-times-dual-booting/)
### Here is the file in *.txt (converted from a *.md before so already can be change into *.md and be written with markdown style):  
[Time.txt](https://github.com/dortania/bugtracker/files/5082073/Time.txt)

**Comment by kommtzeitkonrad** [comment]
https://github.com/acidanthera/OpenCorePkg/blob/40f81f29f74044ae5ad01f2ef8becc9a05bbcbcd/Docs/Configuration.tex#L5714
