### ISSUE TITLE
Autoscrolling of pages in the OC guide is broken

### ISSUE THREAD

**Issue by nagleaidan** [dortania/bugtracker#67]
[Chrome Version 85.0.4183.83 (Official Build) beta (64-bit)], [Windows 10 Edu, 19041.450]

The old guide (`OpenCore-Desktop-Guide`) used to autoscroll if you linked someone to a specific subsection of a page. With the new guide (`OpenCore-Install-Guide`), autoscrolling is not working, at least for me .

To test: go to https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3 and see if it scrolls down to the appropriate section. If it works for you, I'm happy to do more testing on various OS's and web browsers

**Comment by khronokernel** [comment]
Known issue, it's a bug on VuePress's end and so we don't have much control over it. I looked into it a while ago and *partially* fixed it however it's more of a hack which only works if click a link in that page you're on.

If you happen to know any solutions, we'd be more than happy to hear them however unlikely we'll be fixing on our end

**Comment by nagleaidan** [comment]
I'll look into it, had to do some strange stuff with autoscrolling with angular a year ago

**Comment by dhinakg** [comment]
Appears to work now
