### ISSUE TITLE
How would you like me to submit my suggestions?

### ISSUE THREAD

**Issue by richb-hanover** [dortania/bugtracker#69]
I have been working to separate the multiple changes I submitted in a previous PR. To that end, I have created multiple branches in https://github.com/richb-hanover/OpenCore-Install-Guide. See:

* mac-install
* why-oc
* winlin-install
* contributing
* installation-process

I understand those points about style (long lines, etc). Could I get your comments on those branches, so I can know how to submit them as PRs?

I would, of course, be flattered to have these changes incorporated into the main documentation. Thanks.

**Comment by nagleaidan** [comment]
@richb-hanover I am not one the writers for the guide (but am a developer). The general way to get feedback on branches is to submit the PR and then it's easy to see exactly what changes are proposed and have a conversation within the PR comments on anything that needs to be tweaked before merging.

**Comment by richb-hanover** [comment]
Thanks for this response. I did submit a couple PRs, and got shut down pretty hard. See https://github.com/dortania/OpenCore-Install-Guide/pull/147

I offered a response to the PR rejection. Let's see what the team says.
