### ISSUE TITLE
Expand iGPU frame buffer patching

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#7]
At the moment the [iGPU patching guide](https://dortania.github.io/OpenCore-Desktop-Guide/extras/gpu-patches.html) is quite focused on brute forcing with 300 series boards. Would like to expand it more, as this would also allow users to better understand patches mentioned in the laptop guide such as [IvyBridge's DeviceProperties section](https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/ivy-bridge.html#deviceproperties) and allow us to incorporate the "pink tint" fixes. Not a top priority though.

Main topics to discuss:

* [ ] Connector type patching
* [ ] `stolenmem` patching

References:
  * [WEG Manual](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)
  * [CorpNewt's guide: Pink Tint](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake#pink-purple-tint)

**Comment by LucasDondo** [comment]
Yes, I totally agree! I have been trying to fix my stolen memory and other stuff related to framebuffing, and it's difficult to understand through other guides. I believe OpenCore is able to create really self-explanatory and excellent guides, so it'll be awesome if OpenCore's team takes a look into this section of the guide!

**Comment by dhinakg** [comment]
Dortania != Acidanthera (the OpenCore team).
