### ISSUE TITLE
Device-id mistakes in IvyBridge section of vanilla guides

### ISSUE THREAD

**Issue by egar3427** [dortania/bugtracker#77]
OpenCore install guide, IvyBridge processor using a 6-series motherboard. [LINK](https://dortania.github.io/OpenCore-Install-Guide/config.plist/ivy-bridge.html#deviceproperties). 

The guide states if you're using IvyBridge Processor on a 6-series motherboard, you have to add device-id of **3A1C0000** on PciRoot(0x0)/Pci(0x16,0x0). Its actually wrong according to [WhateverGreen Documentations](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md). The correct value is **3A1E0000**. 
OpenCore took forever to boot if the value is wrong.

Here is the screenshots.
What the vanilla guide says:
![Screen Shot 2020-09-14 at 22 12 07](https://user-images.githubusercontent.com/18672175/93104281-d75fc200-f6d7-11ea-8e4a-8ff40b6a4690.png)

The value according to whatevergreen docs.
![Screen Shot 2020-09-14 at 22 11 49](https://user-images.githubusercontent.com/18672175/93104285-da5ab280-f6d7-11ea-98fe-458f054da1ad.png)

The bootlogs I get when using the wrong value from vanilla guides.
![Screen Shot 2020-09-14 at 22 10 09](https://user-images.githubusercontent.com/18672175/93104294-dd55a300-f6d7-11ea-9848-9eb14c6cfadb.png)

Changing it to the correct value immediately solves the problem.

**Comment by khronokernel** [comment]
Oh hrm, I see our issue. For some reason we use the same fake device-id for both Sandy and Ivy, thank you for pointing that out!
Resolved here:
- https://github.com/dortania/OpenCore-Install-Guide/commit/0b041564fa0d9ec20038053eab10b6ae1ce7c8ff
