### ISSUE TITLE
Setup Virtual Map issue on Skylake PC

### ISSUE THREAD

**Issue by quavolution** [dortania/bugtracker#79]
Guide I followed:- [opencore](https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html)

My PC specs :-  intel i5 6402p,  igpu intel HD 510, gigabyte H110m-h mobo

ISSUE :- Hi there, I would like to adress this issue with skylake pc, as you know the guide says specifically that "SetupVirtualMap is not needed on Skylake and newer builds" and I did the same for my pc but it always hangs up just after selecting my Catalina's boot drive on the boot loader. But I was able to fix it by changing back the SetupVertualMap to TRUE  
Current setting that I'm using is this --- "SetupVertualMap=True"
I don't know if the issue is only with my skylake pc or with others too. I am adressing this issue here bc it was hard to find that 'SetupVertualMap" was the problem that was making it freeze some might wouldn't find the fix that's why I thought it's important to adress this for other skylake users.

Link to the page - [SKYLAKE](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#booter)

Thank you for this Unique Guide tho

**Comment by khronokernel** [comment]
Resolved inconsistency here:
https://github.com/dortania/OpenCore-Install-Guide/pull/161

**Comment by quavolution** [comment]
thanks @khronokernel
