### ISSUE TITLE
HM370 chipset - do I neet SSDT-AWAC and SSDT-PMC?

### ISSUE THREAD

**Issue by PhantomR** [dortania/bugtracker#80]
About the "Getting started with ACPI guide": https://dortania.github.io/Getting-Started-With-ACPI/#a-quick-explainer-on-acpi,
the page mentioned says on 300 series motheboards one needs SSDT-AWAC and SSDT-PMC.

However, the laptop table in https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#laptop says I do not need these for Coffee Lake CPU. My laptop has an HM370 chipset, which, I guess, is 300 series. Which page is right?

Also, the individual starting pages for these SSDTs also mention they are needed for 300 series motherboards, but there is no mention of laptop counterparts:
https://dortania.github.io/Getting-Started-With-ACPI/Universal/nvram.html
https://dortania.github.io/Getting-Started-With-ACPI/Universal/awac.html

EDIT: Suggestions: add mention of laptop motherboards on those pages and if, needed, correct the table at the very first link..

Lastly, what about https://dortania.github.io/Getting-Started-With-ACPI/Universal/irq.html ? How do I know if I need this or not?

**Comment by khronokernel** [comment]
HM37 and H370 are slightly different, clarified here:
* https://github.com/dortania/Getting-Started-With-ACPI/commit/12964f00f5a1fe5f2133dd5480a66edd98e909b6
* https://github.com/dortania/Getting-Started-With-ACPI/commit/1540de02a9860a34d15d86cc7e564538b525d12e

Requiring IRQ requirement, see troubleshooting page for when you have boot issues. IRQ is a common culprit:

* https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html
