### ISSUE TITLE
Wrong disable SIP data value for High Sierra

### ISSUE THREAD

**Issue by nducloi107** [dortania/bugtracker#83]
I follow this guide https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#disabling-sip and use data value FF030000 to disable SIP. But it is not working, so I used Terminal in Recovery to disable SIP and I found in Hackintool, the right value is 77020000. I try to reset nvram and the value 7702000 works well.
![Screen Shot 2020-09-20 at 12 08 00 PM](https://user-images.githubusercontent.com/39322375/93694783-fcba5900-fb39-11ea-8df6-1df2d545b7c9.png)

**Comment by khronokernel** [comment]
So looking at [10.13.6's CSR.h file](https://opensource.apple.com/source/xnu/xnu-4570.71.2/bsd/sys/csr.h.auto.html):

```c
CSR_ALLOW_UNTRUSTED_KEXTS = 0x1
CSR_ALLOW_UNRESTRICTED_FS = 0x2
CSR_ALLOW_TASK_FOR_PID = 0x4
CSR_ALLOW_KERNEL_DEBUGGER = 0x8
CSR_ALLOW_APPLE_INTERNAL = 0x10
CSR_ALLOW_DESTRUCTIVE_DTRACE = 0x20
CSR_ALLOW_UNRESTRICTED_DTRACE = 0x40
CSR_ALLOW_UNRESTRICTED_NVRAM = 0x80
CSR_ALLOW_DEVICE_CONFIGURATION = 0x100
CSR_ALLOW_ANY_RECOVERY_OS = 0x200
CSR_ALLOW_UNAPPROVED_KEXTS = 0x400
```

If we add all the values up in a hexadecimal calculator, we get `0x7ff`. You can also verify this yourself, if you're curious why Apple's CSR value in recovery differs from the source is that they omit flags 0x8, 0x20, 0x100 and 0x200. This would result in your 0x277 value, SIP off for consumers does not actually flip all the flags.

If you could explain a bit more *why* you believe the 0x3ff value is correct, that would lead us to a proper conclusion
