### ISSUE TITLE
Dortania Guide

### ISSUE THREAD

**Issue by Emanuele-1998** [dortania/bugtracker#86]
Hi, my friend have Clovertown processor https://ark.intel.com/content/www/it/it/ark/products/28032/intel-xeon-processor-e5345-8m-cache-2-33-ghz-1333-mhz-fsb.html in Dortania guide for config which section do I have to follow?

**Comment by khronokernel** [comment]
We don't officially support that series of CPUs currently, so we recommend following what's closest. So the best match in our guides would be the Nehalem and Westmere sections of the guides
