### ISSUE TITLE
Contributing a Translations

### ISSUE THREAD

**Issue by admarty** [dortania/bugtracker#87]
Hi
I want to contribute a translation for the guide.
But I don't know how to "built with VuePress using Travis-CI and finally hosted on Github Pages".
I have created an account on github.com.
I tried to find tutorials about VuePress and Travis-CI on google but there was nothing clear for me to follow.
I hope you can support me to "sites are built with VuePress using Travis-CI and finally hosted on Github Pages" so I can start translating it.
Thanks

**Comment by LocTran016** [comment]
Actually, you can clone the repo and make the translation in *.md. Translate the title in `.vuepress/config.js` into your language. That's quite enough, I guess

**Comment by admarty** [comment]
> Actually, you can clone the repo and make the translation in *.md. Translate the title in `.vuepress/config.js` into your language. That's quite enough, I guess. Remember to change the token as well

Thank you
