### ISSUE TITLE
Update HEDT sections for Big Sur

### ISSUE THREAD

**Issue by khronokernel** [dortania/bugtracker#88]
With Big Sur nearing release, we'll need to add documentation on the following:

* SSDT-RTC0-RANGE
  * Affects X99, X299 and C series counterparts
  * ~~Unknown if X79 requires this~~. Verified with a few OEMs, not required
* SSDT-UNC
  * Affects X99 and C series counterpart
  * Unknown if X79 requires this

**Comment by kabu0001** [comment]
As far as I know, there are X79 Boards which need the SSDT-RTC0-RANGE, since I needed it on my Rampage IV formula to get past the "beginning pci configuration".
