### ISSUE TITLE
Adding Algolia Docsearch

### ISSUE THREAD

**Issue by LocTran016** [dortania/bugtracker#91]
Would you mind adding the [Docsearch](https://docsearch.algolia.com), it make searching faster (especially search as typing). Thanks

**Comment by khronokernel** [comment]
Not a fan of external services, if possible we'd like to keep things local. One less point of failure, as we're not relying on Docsearch's servers to be up or make sure their cache has been updated in time. Same reason we're not a fan of Travis, it's caused us many issues before and would like to keep everything on one platform
