### ISSUE TITLE
SSDT-AWAC is (probably) needed for Whiskey Lake Laptops

### ISSUE THREAD

**Issue by antoniomcr96** [dortania/bugtracker#92]
https://dortania.github.io/OpenCore-Install-Guide/ktext.html#laptop
In this table it is reported that SSDT-AWAC is needed since 9th gen Coffee Lake processors on Laptops.

I lost several days following the guide because the system didn't boot on a i5-8265u (whiskey lake). After many trials I found out that the problem was SSDT-AWAC. Including it in my EFI made me boot the system for the first time.

All the builds for laptops I've seen include SSDT-AWAC for i5-8265U and i7-8665U (both Whiskey Lake). So I think that the patch is needed.

![image](https://user-images.githubusercontent.com/63928525/96622326-181bae00-130a-11eb-8948-7ea63ab74464.png)

Thanks for all your work!

**Comment by khronokernel** [comment]
Should be corrected now, thanks for mentioning this to us
