### ISSUE TITLE
[BIOS Settings] - SpeedStep-Speedshift

### ISSUE THREAD

**Issue by 1alessandro1** [dortania/bugtracker#94]
Hi, while I was reading [this issue](https://github.com/acidanthera/bugtracker/issues/365#issuecomment-523303086) from acidanthera bugtracker, I saw that some bios settings regarding CPU configuration (MSR 0xE2 Lock etc) were missing from the Bios setitngs at the end of every guide (haswell/kabylake/coffelake/cometlake etc) 

My question is: 

-Should `Speedstep` and `Speedshift` be enabled or not?
-How would this affect system performance? 
-Is `AppleCPUPowerManagement` doing the job ignoring those two BIOS settings or it would be better to at least enable `EIST`?

Hope to hear from you soon, thanks in advance for any clarification on the matter.

**Comment by 1alessandro1** [comment]
Does somebody know anything about it?

**Comment by kadaluarsa** [comment]
@1alessandro1 
speedshift make operating system can control your CPU behaviour.
SpeedStep is native CPU control aka intel technology.
so you have to choose on your own which you prefer

**Comment by PMheart** [comment]
Hello. Please ask questions on forums instead.
