### ISSUE TITLE
Read-only EFI partition currently not supported

### ISSUE THREAD

**Issue by Thireus** [dortania/bugtracker#98]
Currently OpenCore requires write access to the EFI partition in order to function. Several files are written to that partition (not only log files) when OpenCore loads.

Any chance to support read-only EFI partitions in the future?

**Comment by khronokernel** [comment]
Wrong bug tracker, for Acidanthera products please see the respective trackers:
https://github.com/acidanthera/bugtracker

**Comment by Thireus** [comment]
Thank you. Opened here: https://github.com/acidanthera/bugtracker/issues/1242
