### ISSUE TITLE
OpenCore Install Guide: Broken Links

### ISSUE THREAD

**Issue by MikeyClark** [dortania/bugtracker#99]
OpenCore Install Guide 
  Troubleshooting 
    Understanding the macOS Boot Process

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#xnu-kernel-handoff

Both links in the XNU/Kernel Handoff section of the guide titled "Kernel Panic Cannot perform kext summary" and "Kernel Panic on Invalid frame pointer" which lead to a 404 page. The broken links can be found above the second screenshot in that section. (I am for whatever reason not able to attach a screenshot in this post.)

A possible fix would be to re-link the correct pages to correct the error.

**Comment by khronokernel** [comment]
Oh thank you for bringing this to our attention, seems when we rewrote the troubleshooting page we didn't correctly update the hyperlinks. Resolved [here](https://github.com/dortania/OpenCore-Install-Guide/commit/a154768e06cfde3d251dd3820a705eb4f7288cb6), this PR will be merged Monday with 0.6.3's release.
